import { execFileSync } from 'node:child_process'
import {
  cpSync,
  existsSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import ts from 'typescript'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { EMPTY_MAP, TYPES_SPECIFIER } from '../../src/emit-map'
import {
  assertHoverBudget,
  assertNoDiagnostics,
  createTypeHarness,
} from '../types/harness'
import type { Compilation } from '../types/harness'

/**
 * Layer 3: the map, produced by a **real Nuxt build** rather
 * than by calling the emitter.
 *
 * This is the layer nothing else substitutes for. Every other assertion in this
 * package runs against handler records written by hand; only this one catches
 * the type-generation hook silently ceasing to fire, which is the single most
 * likely thing a Nuxt or Nitro patch release breaks.
 *
 * ## Why it runs against a copy of the playground
 *
 * The sources are the playground's, copied byte for byte — the app under test
 * is itself the e2e fixture. Two reasons for the copy, and neither of them is
 * fastidiousness:
 *
 * - The path-referentiality claim can only be made by **editing a
 *   catalogue and rebuilding**, and `test/e2e/specifiers.test.ts` boots a server out
 *   of the same directory. Mutating tracked sources under a sibling suite's feet
 *   is a race, and the alternative — serialising the whole suite — would slow
 *   every run to pay for one assertion.
 * - A copy makes this file independent of whether anything else ran
 *   `nuxt prepare` first, so a failure here is always about this ticket.
 *
 * `node_modules` is symlinked rather than copied, which is what keeps the copy a
 * real consumer: the module resolves through its published `exports` map and
 * every generated `paths` entry points back at the package's own `dist/`.
 *
 * ## Why the central assertion is a *rendering* one
 *
 * Declaration emit writes type references as `import("…")` type nodes. One that
 * does not resolve inside a `.d.ts` produces **no diagnostic** under
 * `skipLibCheck`, which every Nuxt-generated tsconfig sets: the entry becomes
 * TypeScript's error type, which renders as `any` but satisfies every
 * `Expect<Equal<…>>` and every `IsAny` check made against it.
 * Measured for this ticket by emitting the map
 * one directory too high — the whole playground compiled clean apart from the
 * single *control-flow* assertion in `app.vue`. So the claim made here is that
 * the union **renders with this route's real tags**: the harness refuses to
 * render `any`, and that refusal is the check that bites.
 */

const PACKAGE_ROOT = fileURLToPath(new URL('../..', import.meta.url))
const PLAYGROUND = join(PACKAGE_ROOT, 'playground')

/**
 * Where the map must land: Nitro's `typesDir` is `resolve(buildDir, 'types')`,
 * and Nuxt hands Nitro its own `buildDir`.
 *
 * Written out rather than imported from `src/module.ts`. That is the point —
 * the emitter computes every specifier relative to this directory, so a test
 * that took the path from the code under test would follow the file wherever it
 * moved and stay green. Restating it is what makes the "emitted one level too
 * high" mutation red.
 */
const MAP_PATH = join('.nuxt', 'types', 'nuxt-handler-errors.d.ts')

/**
 * The value specifier the probe imports the reader through.
 *
 * Written out rather than derived from `TYPES_SPECIFIER`, for the reason
 * `MAP_PATH` is: this file's job is to check what a *consumer* can resolve, and
 * a derivation would follow the export map wherever it went. The probe is
 * compiled inside the prepared app, so this is the published `exports` entry
 * being exercised rather than a relative source import.
 */
const SHARED_SPECIFIER = '@dphonys/nuxt-handler-errors-old/shared'

/** Build output and installed packages: regenerated by `prepare`, or symlinked. */
const NOT_COPIED = /[/\\](?:node_modules|\.nuxt|\.output|\.turbo|dist)$/

/** The generated tsconfigs the hoist entry has to reach: app, server, shared. */
const GENERATED_TSCONFIGS = [
  'tsconfig.json',
  'tsconfig.server.json',
  'tsconfig.shared.json',
]

/**
 * The `/// <reference>` each context reaches the map through, and the
 * `addTypeTemplate` flag that puts it there.
 *
 * Naming the flag beside the file is the point: the obvious snippet
 * passes `{ nitro: true }`, which buys the third row and silently drops the
 * other two.
 */
const CONTEXT_REFERENCES = [
  { flag: 'nuxt', file: join('.nuxt', 'nuxt.d.ts') },
  { flag: 'shared', file: join('.nuxt', 'nuxt.shared.d.ts') },
  { flag: 'nitro', file: join('.nuxt', 'types', 'nitro-nuxt.d.ts') },
]

/** Every `/api` route the playground serves, keyed as Nitro keys it. */
const EXPECTED_ROUTE_KEYS = [
  "'/api/boom': {",
  "'/api/chain/a': {",
  "'/api/chain/b': {",
  "'/api/chain/c': {",
  "'/api/context-echo': {",
  "'/api/event-typed-fetch-probe': {",
  "'/api/method-fallback': {",
  "'/api/rogue-status': {",
  "'/api/specifier-probe': {",
  "'/api/users/:id': {",
]

/** The tags of the three variants `/api/users/:id` declares. */
const DECLARED_TAGS = ['user-not-found', 'user-suspended', 'forbidden']

/**
 * The hover a caller consults while writing their `switch`, budgeted against
 * the **real** generated map.
 *
 * measured 182 flat / 353 as the `SerializeObject` residue the same union
 * renders outside the `if (failure)` guard — set at ~1.5× the good value.
 */
const READER_VARIANT_BUDGET = 275

/**
 * The error-hover budget `H_error`, which ticket 05 deferred to the first
 * surface where the union arrives through an *instantiated generic*.
 *
 * measured 212 with
 * `Flatten` inside `TypedErrorRef`'s body / 371 as the `SerializeObject`
 * residue without it — see the assertion for why the *position* `Flatten` is
 * written in is the whole of the mandate.
 */
const H_ERROR_BUDGET = 260

/**
 * `$typedFetch.safe`'s **whole result** — the hover a caller lands on first on
 * this surface, since the discriminant lives inside the object rather than
 * beside it.
 *
 * measured 273 with `Flatten` inside `TypedResult`'s body /
 * 432 as the `SerializeObject` residue without it. Set at ~1.25× the good
 * value, which is the ratio `H_error` also lands on: a 1.58×
 * spread is thin by the 2–20× standard, so the categorical half of the
 * assertion carries the weight.
 */
const SAFE_RESULT_BUDGET = 340

/**
 * `event.$typedFetch.safe`'s whole result, hovered in the **server** program.
 *
 * `Event$TypedFetch.safe` is the same `TypedFetchSafe` the global carries
 * (the surface adds context forwarding, not a second type), and
 * the measurement agrees: **273 flat here, the global's own number** / 432 as
 * the `SerializeObject` residue that spelling measured without
 * `Flatten`. Budgeted separately at the same ~1.25× anyway — the two programs
 * render through different `paths` and different ambient declarations, and one
 * number standing for both would hide which program regressed.
 */
const EVENT_SAFE_RESULT_BUDGET = 340

/**
 * The tags `/api/method-fallback`'s `default` handler declares, which a `GET`
 * reaches only through the presence-based fallback.
 */
const FALLBACK_TAGS = ['unauthorized', 'forbidden']

/**
 * What the emitted map's handler specifiers are rewritten to, to break them.
 *
 * Every specifier in the file is relative to `.nuxt/types`, so redirecting the
 * one directory they all traverse points every one of them at nothing — which
 * is precisely what emitting the file to the wrong place would do, and what
 * `pathe.relative` returning a bare name would do.
 */
const BROKEN_SPECIFIER_REWRITE = {
  from: `'../../server/`,
  to: `'../../nowhere/`,
}

/**
 * Where the compile-time probe is written.
 *
 * `.nuxt/` is a dot-directory, which TypeScript's wildcard expansion skips — so
 * the probe is invisible to `vue-tsc`, to eslint and to knip, and reaches the
 * program only as the harness's explicit root file. Everything it imports
 * arrives through the generated tsconfig's `paths`.
 */
const PROBE_PATH = join('.nuxt', 'handler-errors-probe.ts')

/**
 * Where the **server-program** probe is written — beside `PROBE_PATH` and
 * invisible for the same reasons, but compiled against the generated
 * `tsconfig.server.json`. `event.$typedFetch` hangs off h3's `H3Event`, and the
 * server program is the one a handler author's call site is typed in — the
 * probe above cannot reach it, because the app program types `H3Event` too and
 * a hover there would say nothing about the program the surface is used from.
 */
const SERVER_PROBE_PATH = join('.nuxt', 'handler-errors-server-probe.ts')

const WORKSPACE = mkdtempSync(join(tmpdir(), 'nuxt-handler-errors-app-'))

afterAll(() => {
  rmSync(WORKSPACE, { recursive: true, force: true })
})

function probeSource(): string {
  const vocabulary = join(PACKAGE_ROOT, 'test/types/vocabulary')

  return [
    `import type { MatchedRoutes } from 'nitropack/types'`,
    `import { useFetch } from '#app'`,
    `import type { NuxtError } from '#app'`,
    `import { useTypedFetch } from '#imports'`,
    `import { declaredError } from '${SHARED_SPECIFIER}'`,
    `import type { DeclaredErrorBody, DeclaredErrorsOf, TypedApiErrors } from '${TYPES_SPECIFIER}'`,
    `import type { Equal, Expect, IsAny, IsNever } from '${vocabulary}'`,
    ``,
    `declare module '${TYPES_SPECIFIER}' {`,
    `  interface TypedApiErrors {`,
    // The transient state, declared rather than raced for: this map
    // lands ~26 ms *ahead* of Nitro's, so for that window it holds a key
    // `InternalApi` does not.
    `    '/api/ghost': { get: { tag: 'ghost', status: 404 } }`,
    `  }`,
    `}`,
    ``,
    `export type Declared = TypedApiErrors['/api/users/:id']['get']`,
    ``,
    // Resolved against the app's *real* generated `InternalApi`.
    `export type Ghost = MatchedRoutes<'/api/ghost'>`,
    `type _ghostIsUnreachable = Expect<IsNever<Ghost>>`,
    ``,
    // ---- ticket 08, the lookup -------------------------------------------
    //
    // A call-site *literal*, resolved through Nitro's own route matching
    // against this app's really-generated `InternalApi` — `42` finds
    // `/api/users/:id` by the same scoring Nitro uses for the success type.
    `export type Lookup = DeclaredErrorsOf<'/api/users/42'>`,
    // The presence-based fallback, on a route that really does have a branded
    // `default` handler and an unbranded `post` sibling beside it.
    `export type LookupFallback = DeclaredErrorsOf<'/api/method-fallback'>`,
    // The key the map holds and `InternalApi` does not, one layer up from
    // `Ghost` above.
    `export type LookupGhost = DeclaredErrorsOf<'/api/ghost'>`,
    // The island-renderer case, at the lookup: Nuxt keys `/__nuxt_island/**` to
    // `#internal/nuxt/island-renderer`, which `resolveNitroPath` does not
    // resolve, so this entry is TypeScript's error type and `MatchedRoutes`
    // reaches it. Rendered rather than asserted, because the error type
    // satisfies every `Expect<Equal<…>>` written against it.
    `export type LookupIsland = DeclaredErrorsOf<'/__nuxt_island/foo'>`,
    ``,
    // **Deliberately vacuous against a broken map.** Both are true of this app
    // and both stay green when every specifier in the map resolves to nothing,
    // which is the whole reason the claims that matter are rendering ones.
    //
    // Written as a claim about *one* variant's payload rather than about the
    // whole tag set, so that the catalogue edit in the path-referentiality
    // block below — which adds a variant on purpose — does not falsify it.
    `type _lookupPayload = Expect<`,
    `  Equal<Extract<Lookup, { tag: 'forbidden' }>['requiredRole'], 'admin' | 'owner'>>`,
    `type _lookupMatchesTheRawEntry = Expect<Equal<Lookup, Declared>>`,
    ``,
    // ---- ticket 09, the reader -------------------------------------------
    //
    // The *"flat variant
    // union"* hover, measured against the **real** generated map rather
    // than a hand-written union — the only place the `Simplify<Serialize<…>>`
    // the emitter writes is the thing being rendered.
    `declare const declaredFailure:`,
    `  { data?: DeclaredErrorBody<DeclaredErrorsOf<'/api/users/42'>> }`,
    `export const ReaderReturn = declaredError(declaredFailure)`,
    // The union as a caller reaches it: *inside* the `if (failure)` guard,
    // which is the only place it is inhabited and the only place a `switch`
    // gets written. `ReaderReturn` itself is `… | undefined`, and that union
    // wrapper is what stops the printer expanding the alias.
    `export type ReaderVariant = NonNullable<typeof ReaderReturn>`,
    // The reader is a path, not a transform: what comes back is the map's own
    // union, unchanged. Vacuous against a broken map for the usual reason, and
    // the renders above are what are not.
    `type _readerReturnsTheLookup = Expect<`,
    `  Equal<typeof ReaderReturn, DeclaredErrorsOf<'/api/users/42'> | undefined>>`,
    // `Equal` passes with `any` on either side, and this is
    // the one file where a collapse to TypeScript's error type is a *measured*
    // history rather than a hypothetical.
    // The render below is the primary guard; this is the cheap second one.
    `type _readerVariantIsNotAny = Expect<Equal<IsAny<ReaderVariant>, false>>`,
    ``,
    // ---- ticket 10, the composable ---------------------------------------
    //
    // Reached through `#imports`, which is what a consumer's own call site
    // resolves: the composable imports `useFetch` from `#app`, so it cannot sit
    // on any of the three published specifiers and its `addImports`
    // registration is the whole contract. This is
    // therefore also the assertion that the registration happened at all.
    // **The two framework names are imported for the render's sake**, not for
    // an assertion: a name the fixture does not import renders as
    // `import("…").Name`, and the budgets were taken in an editor,
    // where a call site's own file has them in scope. The alias below is what
    // keeps the imports used, and it names no route so a broken map cannot
    // reach it.
    `type _Envelope = NuxtError<DeclaredErrorBody<{ tag: string; status: 1 }>>`,
    ``,
    // **Rendering targets only.** Every structural claim about the composable
    // lives in `playground/app.vue`, deliberately: measured, an
    // `Expect<Equal<typeof typed.error.value, NuxtError<DeclaredErrorBody<…>>>>`
    // written here goes **red** against the broken-specifier fork below, which
    // would quietly convert this file's central demonstration — that structural
    // assertions are blind to a map that has stopped meaning anything — into a
    // file that no longer demonstrates it.
    `const typed = await useTypedFetch('/api/users/42')`,
    // The envelope-shaped hover, and the flat variant union reached
    // through this composable rather than through a hand-declared carrier.
    `export type TypedErrorValue = NonNullable<typeof typed.error.value>`,
    `export const TypedReaderReturn = declaredError(typed.error.value)`,
    `export type TypedReaderVariant = NonNullable<typeof TypedReaderReturn>`,
    ``,
    // The degradation lock against the app's **real** `InternalApi`,
    // where `MatchedRoutes` has this app's seven keys to score rather than
    // none. `/api/boom` is a plain `defineEventHandler`.
    `const typedUndeclared = await useTypedFetch('/api/boom')`,
    `const vanillaUndeclared = await useFetch('/api/boom')`,
    `export const TypedUndeclaredError = typedUndeclared.error`,
    `export const VanillaUndeclaredError = vanillaUndeclared.error`,
    ``,
    // The presence-based method fallback, reached through the
    // composable's own `Method` type parameter rather than through the lookup
    // directly — which is the only thing that proves the composable forwards
    // the method at all. Row 2: `post` is present and unbranded, so the error
    // collapses back to vanilla's. Row 1: no method named, `get` absent, so the
    // `default` handler's union.
    `const typedPost = await useTypedFetch('/api/method-fallback',`,
    `  { method: 'POST' })`,
    `export const TypedPostError = typedPost.error`,
    `const typedFallback = await useTypedFetch('/api/method-fallback')`,
    `export const TypedFallbackReturn = declaredError(typedFallback.error.value)`,
    `export type TypedFallbackVariant = NonNullable<typeof TypedFallbackReturn>`,
    ``,
    // ---- ticket 11, the imperative surface -------------------------------
    //
    // **No import.** `$typedFetch` is a global, declared the way Nitro declares
    // its own `$fetch` — the type arrives with the emitted map, which imports
    // `/types` and its `declare global` block. That this line resolves at all
    // is therefore also the assertion that the declaration reaches a real app
    // program.
    `const safe = await $typedFetch.safe('/api/users/42')`,
    // The union as a caller reaches it: *inside* the `if (!safe.ok)` guard,
    // which is where a `switch` gets written. There is no `| undefined` on this
    // surface to keep the printer from expanding the alias — the discriminant
    // does that job — so the narrowed form is the only form.
    // What a caller hovers on the result, and what they hover once they are
    // inside `if (!safe.ok)` and writing the `switch`.
    `export type SafeResult = typeof safe`,
    `export type SafeError = Extract<typeof safe, { ok: false }>['error']`,
    // The degradation collapse against the app's real `InternalApi`: an
    // undeclared route's result has one arm, so `ok` is the literal `true`.
    // **Rendered, not asserted structurally** — an `Expect<Equal<…, true>>`
    // here goes red against the broken-specifier fork below, where `/api/boom`
    // resolves to TypeScript's error type, which would convert this file's
    // central demonstration into a file that no longer demonstrates it.
    `const safeUndeclared = $typedFetch.safe('/api/boom')`,
    `export type UndeclaredSafeOk = Awaited<typeof safeUndeclared>['ok']`,
    // The throwing form is vanilla's, byte for byte, in a program where
    // `MatchedRoutes` has this app's real keys to score.
    `const typedThrown = await $typedFetch('/api/users/42')`,
    `const vanillaThrown = await $fetch('/api/users/42')`,
    `export type TypedThrown = typeof typedThrown`,
    `export type VanillaThrown = typeof vanillaThrown`,
    ``,
  ].join('\n')
}

/**
 * The playground files that reach into this suite for the fixed
 * assertion vocabulary, with the relative spelling each one uses.
 *
 * Listed rather than globbed so that a file quietly losing the import is a
 * failure here instead of a silently skipped rewrite.
 */
const SUITE_IMPORTERS = [
  ['app.vue', '../test/types/vocabulary'],
  ['server/api/chain/a.get.ts', '../../../../test/types/vocabulary'],
  ['server/api/users/[id].get.ts', '../../../../test/types/vocabulary'],
  ['server/api/method-fallback.ts', '../../../test/types/vocabulary'],
  ['shared/lookup-probe.ts', '../../test/types/vocabulary'],
] as const

/**
 * Re-point the playground's reaches into the suite at an absolute path.
 *
 * Those imports are written relative to the playground, which lands nowhere out
 * of a copy in the system temp directory. Left alone each is a `TS2307`
 * standing between this file and a clean program, which is worth more than
 * the edit costs: without a clean-program assertion a fixture that stopped
 * compiling for an unrelated reason would pass while proving nothing.
 */
function reanchorSuiteImports(root: string): void {
  for (const [file, specifier] of SUITE_IMPORTERS) {
    const path = join(root, file)
    const source = readFileSync(path, 'utf8')
    const reanchored = source.replace(
      `'${specifier}'`,
      `'${join(PACKAGE_ROOT, 'test/types/vocabulary')}'`
    )

    if (reanchored === source) {
      throw new Error(
        `Expected ${path} to import the suite vocabulary as '${specifier}'.`
      )
    }

    writeFileSync(path, reanchored)
  }
}

/**
 * An emitted map with its route blocks removed — the banner, the two imports,
 * the `declare module` wrapper and the closing `export {}`.
 *
 * Route blocks are the only lines the emitter indents four spaces, which is why
 * that is the filter.
 */
function fileShell(source: string): string {
  return source
    .split('\n')
    .filter((line) => !line.startsWith('    '))
    .join('\n')
}

/** One prepared app tree: where it is and what the module wrote into it. */
interface BuiltTree {
  readonly root: string
  /** The emitted map's text, so path-referentiality can be a byte comparison. */
  readonly map: string
}

/** One built app: a tree plus its compiled probe. */
interface BuiltApp extends BuiltTree {
  readonly compilation: Compilation
}

/**
 * The prepared trees, keyed by name and built **once per process** — the
 * builds are the expensive half, and several blocks below probe the same
 * tree.
 */
const builtTrees = new Map<string, BuiltTree>()

/**
 * Copy the playground, optionally edit it, run `nuxt prepare` and read back
 * what the module wrote — once; later calls under the same name reuse the
 * tree.
 *
 * `nuxt prepare` rather than a full build: `types:extend` fires inside Nitro's
 * `writeTypes`, which is exactly what `prepare` runs, and it costs ~2.5s.
 */
function ensureBuiltTree(
  name: string,
  edit?: (root: string) => void
): BuiltTree {
  const existing = builtTrees.get(name)
  if (existing !== undefined) return existing

  const root = join(WORKSPACE, name)

  cpSync(PLAYGROUND, root, {
    recursive: true,
    filter: (source) => !NOT_COPIED.test(source),
  })
  symlinkSync(join(PLAYGROUND, 'node_modules'), join(root, 'node_modules'))
  reanchorSuiteImports(root)
  edit?.(root)

  execFileSync(
    join(PACKAGE_ROOT, 'node_modules/.bin/nuxt'),
    ['prepare', root],
    {
      cwd: PACKAGE_ROOT,
      stdio: 'pipe',
    }
  )

  const mapPath = join(root, MAP_PATH)
  if (!existsSync(mapPath)) {
    throw new Error(
      [
        `\`nuxt prepare\` produced no map at ${MAP_PATH}.`,
        'Either the type template was never registered, or it was emitted',
        "somewhere other than Nitro's types directory — where every specifier",
        'in it would resolve to nothing, silently.',
      ].join('\n')
    )
  }

  const tree: BuiltTree = { root, map: readFileSync(mapPath, 'utf8') }
  builtTrees.set(name, tree)

  return tree
}

/**
 * The server-program probe: `event.$typedFetch` hovered where a handler author
 * writes it.
 *
 * `/api/users/42` rather than a route parameter for the reason the app probe
 * uses it — the literal is matched to `/api/users/:id` by Nitro's own scoring,
 * so the render carries the callee's declared tags only if the whole chain
 * (augmentation → global declaration → map entry → handler specifier) resolved
 * against the really-generated map.
 */
function serverProbeSource(): string {
  return [
    `import type { H3Event } from 'h3'`,
    ``,
    // Declared rather than taken from a `defineEventHandler` callback: the
    // harness hovers top-level declarations only, and the parameter's type is
    // exactly this. What the declaration cannot fake is the member — h3's own
    // `H3Event` has no `$typedFetch`, so the call below resolving at all is
    // also the assertion that the module's augmentation reaches a real server
    // program.
    `declare const event: H3Event`,
    ``,
    `const safe = await event.$typedFetch.safe('/api/users/42')`,
    `export type EventSafeResult = typeof safe`,
    ``,
  ].join('\n')
}

/**
 * Write the server probe into an already-prepared app root and compile it
 * against the generated server program.
 *
 * A `Compilation` rather than a `BuiltApp`: the map was already read and
 * asserted on by the app-program probe of the same root, and re-reading it
 * here would only invite asserting the same bytes twice.
 */
function probeServerApp(root: string): Compilation {
  writeFileSync(join(root, SERVER_PROBE_PATH), serverProbeSource())

  const harness = createTypeHarness({
    ts,
    rootDir: root,
    tsconfigPath: join(root, '.nuxt/tsconfig.server.json'),
  })

  return harness.compileAlone(join(root, SERVER_PROBE_PATH))
}

/** Write the probe into an already-prepared tree and compile it. */
function probeApp(tree: BuiltTree): BuiltApp {
  writeFileSync(join(tree.root, PROBE_PATH), probeSource())

  const harness = createTypeHarness({
    ts,
    rootDir: tree.root,
    tsconfigPath: join(tree.root, '.nuxt/tsconfig.json'),
  })

  return {
    ...tree,
    compilation: harness.compileAlone(join(tree.root, PROBE_PATH)),
  }
}

/**
 * A byte copy of an already-built tree whose emitted map has had every handler
 * specifier pointed at a directory that is not there. Memoized like the
 * builds it forks from.
 *
 * The build is not repeated — nothing about `nuxt prepare` is under test here,
 * only what the compiler does with a map that has stopped meaning anything, and
 * the copy sits beside its original at the same depth so every relative path in
 * the generated tsconfigs still resolves.
 */
function ensureBrokenFork(from: BuiltTree, name: string): BuiltTree {
  const existing = builtTrees.get(name)
  if (existing !== undefined) return existing

  const root = join(WORKSPACE, name)

  cpSync(from.root, root, { recursive: true })

  const broken = from.map.replaceAll(
    BROKEN_SPECIFIER_REWRITE.from,
    BROKEN_SPECIFIER_REWRITE.to
  )
  if (broken === from.map) {
    throw new Error(
      `Expected the emitted map to spell its specifiers ${BROKEN_SPECIFIER_REWRITE.from}…`
    )
  }

  writeFileSync(join(root, MAP_PATH), broken)

  const tree: BuiltTree = { root, map: broken }
  builtTrees.set(name, tree)

  return tree
}

let app: BuiltApp

beforeAll(() => {
  // The tree builds once; the probe compile it feeds is the most expensive
  // program in the repo.
  app = probeApp(ensureBuiltTree('base'))
}, 600_000)

describe('the generated map, in a real Nuxt app', () => {
  it('compiles the whole app clean, with the map in the program', () => {
    // The clean-program assertion, and the reason every claim below can be believed:
    // without it a probe that stopped compiling for an unrelated reason would
    // take the rendering assertions down with it silently. Nothing is filtered
    // by file — a positive fixture whose *app* stopped compiling is not a
    // passing fixture.
    assertNoDiagnostics(app.compilation)
  })

  it('lands in Nitro’s own types directory, under the build directory', () => {
    // `buildApp` throws if it is not there, so this records what the file is.
    // The directory is not a preference: every specifier in the
    // file is relative to it, and moving the file one level up leaves the whole
    // map resolving to nothing with no diagnostic anywhere.
    expect(app.map).toContain('Generated by @dphonys/nuxt-handler-errors-old')
  })

  it('seeds a cold start with the same file shell it later replaces', () => {
    // The third reason for a type template: `nuxi dev` races
    // `writeTypes` against `buildNuxt`, so the template can be asked for its
    // contents before `nitro:init` has fired, and a `/// <reference>` to a file
    // that is not a module is a dangling one.
    //
    // **This currently holds by construction** — `EMPTY_MAP` is the emitter's
    // own `renderFile` applied to no routes — and saying so is the point. The
    // regression it guards against is the seed being spelled a second time,
    // which is where it was written first and what would let a banner, a
    // specifier or the closing `export {}` drift with nothing to notice. The
    // cold-start render itself is not observable from here: by the time
    // `prepare` returns, the populated one has already replaced it. `pnpm
    // dev-race` is where a genuinely cold start happens.
    expect(fileShell(EMPTY_MAP)).toBe(fileShell(app.map))
  })

  it('keys every route the app serves, and keys them as Nitro does', () => {
    for (const key of EXPECTED_ROUTE_KEYS) expect(app.map).toContain(key)

    // Nitro's own `[id]` → `:id` rewrite and its own extension stripping,
    // arrived at by re-running Nitro's loop rather than reimplementing it.
    expect(app.map).toContain(
      `typeof import('../../server/api/users/[id].get').default`
    )
  })

  it('augments the module’s own specifier, and closes as a module', () => {
    // Never Nitro's namespace: a future Nitro release owning
    // this name would break consumers silently, and `TypedApiErrors` appears in
    // every wrapper signature, so declaring it there would hand this module's
    // public surface a second owner.
    expect(app.map).toContain(`declare module '${TYPES_SPECIFIER}' {`)
    expect(app.map).not.toContain(`declare module 'nitropack/types'`)
    expect(app.map.trimEnd().endsWith('export {}')).toBe(true)
  })

  it('is hoisted onto every generated tsconfig', () => {
    // A load-bearing string, asserted through its effect.
    // Removing `typescript.hoist.push(…)` empties all three of these.
    for (const config of GENERATED_TSCONFIGS) {
      expect(readFileSync(join(app.root, '.nuxt', config), 'utf8')).toContain(
        `"${TYPES_SPECIFIER}"`
      )
    }
  })

  it('is referenced from the app, shared and server programs', () => {
    for (const { flag, file } of CONTEXT_REFERENCES) {
      expect(
        readFileSync(join(app.root, file), 'utf8'),
        `addTypeTemplate({ …, ${flag}: true }) should have written ${file}`
      ).toContain('nuxt-handler-errors.d.ts')
    }
  })

  it('resolves: the declared union carries this route’s real tags', () => {
    // The assertion this whole file exists for. Tags render **double**-quoted:
    // they are synthesised by the checker out of an object literal's inferred
    // type rather than written in an annotation.
    const rendered = app.compilation.renderHover('Declared')

    for (const tag of DECLARED_TAGS) expect(rendered).toContain(`"${tag}"`)
    expect(rendered).toContain('requiredRole')
  })

  it('keys the divergence case as a default plus an unbranded sibling', () => {
    // What makes the method-fallback's three rows observable at all: one route, two
    // handler files, one of them branded and keyed `default`.
    expect(app.map).toContain(
      `typeof import('../../server/api/method-fallback').default`
    )
    expect(app.map).toContain(
      `typeof import('../../server/api/method-fallback.post').default`
    )
  })

  it('resolves: a route literal names this route’s real tags', () => {
    // Ticket 08's central claim, and a rendering one for the reason the whole
    // file exists: `'/api/users/42'` is matched to the `'/api/users/:id'` entry
    // by Nitro's own scoring, and what comes back carries this route's tags. An
    // `Expect<Equal<…>>` over the same lookup is in the probe and is green even
    // when the map means nothing — see the broken-specifier block below.
    const rendered = app.compilation.renderHover('Lookup')

    for (const tag of DECLARED_TAGS) expect(rendered).toContain(`"${tag}"`)
    expect(rendered).toContain('requiredRole')
  })

  it('resolves: a GET reaches the default handler’s union by presence', () => {
    // The fallback's row 1, rendered. The three rows are asserted structurally
    // in `playground/server/api/method-fallback.ts`, beside the handlers; this
    // is the half that proves the union on the other side of the fallback is a
    // real one rather than TypeScript's error type.
    const rendered = app.compilation.renderHover('LookupFallback')

    for (const tag of FALLBACK_TAGS) expect(rendered).toContain(`"${tag}"`)
  })

  it('resolves: the reader hands back this route’s real tags', () => {
    // Ticket 09's central claim, and a rendering one for the same reason as the
    // two above: an `Expect<Equal<…>>` over the reader's return is green
    // against a map whose specifiers resolve to nothing.
    const rendered = app.compilation.renderHover('ReaderReturn')

    for (const tag of DECLARED_TAGS) expect(rendered).toContain(`"${tag}"`)
    expect(rendered).toContain('requiredRole')
    expect(rendered).toContain('undefined')
  })

  it('renders the reader’s variant flat, in budget, against the real map', () => {
    // The legibility grade for this row — *"the reader's
    // return | the flat variant union | this is what callers read"* —
    // taken as a measurement rather than inherited as a claim.
    //
    // **Why the narrowed spelling.** `ReaderReturn` is `… | undefined`, and
    // measured on this app that union wrapper is worth 171 characters: the
    // printer expands a top-level alias and echoes a nested one, so the
    // pre-narrowing hover is 353 characters of `SerializeObject` residue while
    // the same type inside the `if (failure)` guard is 182 and
    // flat. The guard is where a `switch` gets written, so
    // the guard is what is budgeted.
    const rendered = assertHoverBudget(app.compilation, {
      name: 'ReaderVariant',
      max: READER_VARIANT_BUDGET,
    })

    for (const tag of DECLARED_TAGS) expect(rendered).toContain(`"${tag}"`)
    expect(rendered).toContain('requiredRole')
    // Length alone would pass a residue that happened to be short; this is the
    // known residue regression, checked by name.
    expect(rendered).not.toContain('SerializeObject')
  })

  it('renders the composable’s error ref flat, in budget', () => {
    // **The `H_error` measurement, written at last** — ticket 05 deferred this
    // measurement to the first surface where the union arrives through an
    // *instantiated generic* rather than a hand-written annotation, and this is
    // it. Measured against the real playground map, in the fixture's own
    // spelling (the two framework names imported, as an editor's file has
    // them):
    //
    // | spelling | chars | shape |
    // | --- | --- | --- |
    // | `Flatten` inside `TypedErrorRef`'s body — shipped | **212** | flat |
    // | no `Flatten` | **371** | `Simplify<SerializeObject<…>>` residue |
    // | `Flatten` passed in as `TypedErrorRef`'s third argument | 380 | residue |
    //
    // The flat-render mandate reproduces exactly, and row 3 is why it once
    // seemed not to: `Flatten` written where the printer
    // can still see its alias — as a type argument, or by hand in the
    // annotation being rendered — echoes `Flatten<Simplify<…>>` and is one name
    // *longer* than doing nothing. Written inside the alias body it is resolved
    // during instantiation and there is nothing left to echo.
    //
    // The budget is the original number, untouched. The harness emits
    // `import("…")` prefixes for names this probe does not import and
    // canonicalizes their specifiers before measuring, which is what lands
    // the measurement back on 212 machine-stably. **The length is the
    // weaker half of the assertion** — a 1.75× spread is thin by the 2–20×
    // standard — so the categorical half is checked too: `SerializeObject`
    // present or absent.
    const rendered = assertHoverBudget(app.compilation, {
      name: 'TypedErrorValue',
      max: H_ERROR_BUDGET,
    })

    expect(rendered).toContain('NuxtError')
    expect(rendered).toContain('DeclaredErrorBody')
    expect(rendered).not.toContain('SerializeObject')
    // And it is this route's real union rather than TypeScript's error type,
    // which is the claim an `Expect<Equal<…>>` cannot make.
    for (const tag of DECLARED_TAGS) expect(rendered).toContain(`"${tag}"`)
    expect(rendered).toContain('requiredRole')
  })

  it('renders the composable’s variant flat, in budget, through the reader', () => {
    // The flat variant union — *"the reader's return | the flat variant union |
    // this is what callers read"* — reached the way a caller reaches it: out of
    // `useTypedFetch`'s own error ref rather than out of a hand-declared
    // carrier. The pair is **182 flat / 431 as the envelope-shaped hover
    // above**, a 2.4× spread, which is what makes this position budgetable
    // where the envelope itself is not.
    const rendered = assertHoverBudget(app.compilation, {
      name: 'TypedReaderVariant',
      max: READER_VARIANT_BUDGET,
    })

    for (const tag of DECLARED_TAGS) expect(rendered).toContain(`"${tag}"`)
    expect(rendered).toContain('requiredRole')
    expect(rendered).not.toContain('SerializeObject')
  })

  it('leaves an undeclared route byte-identical to vanilla, in a real app', () => {
    // The degradation lock where `MatchedRoutes` has this app's
    // seven real keys to score rather than none — which is the half
    // `test/types/use-typed-fetch.ts` cannot reach, and the half where a
    // route-matching mistake would show.
    const typed = app.compilation.renderHover('TypedUndeclaredError')

    expect(typed).toBe(app.compilation.renderHover('VanillaUndeclaredError'))
    expect(typed).toContain('NuxtError<unknown>')
    expect(typed).not.toContain('DeclaredErrorBody')

    // Row 2 of the method table, through the composable: `post` is
    // present on this route and unbranded, so it collapses back to vanilla's
    // envelope rather than inheriting the `default` handler's union.
    expect(app.compilation.renderHover('TypedPostError')).toBe(typed)
  })

  it('resolves: a GET through the composable reaches the fallback union', () => {
    // Row 1 of the same table, and the control for the row above — without it
    // "the method reached the lookup" would be indistinguishable from "the
    // lookup answered `never` for both".
    const rendered = app.compilation.renderHover('TypedFallbackVariant')

    for (const tag of FALLBACK_TAGS) expect(rendered).toContain(`"${tag}"`)
  })

  it('renders `.safe`’s result flat, in budget, against the real map', () => {
    // The flat-render mandate on the imperative surface. Measured against the
    // real playground map, on the hover a caller lands on first:
    //
    // | spelling | chars | shape |
    // | --- | --- | --- |
    // | `Flatten<D>` inside `TypedResult`'s body — shipped | **273** | flat |
    // | no `Flatten` anywhere | **432** | `Simplify<SerializeObject<…>>` |
    // | a `TypedResult<…, Flatten<…>>` argument | 333 | flat |
    //
    // Row 3 is the alias-echo pitfall from a third position, and it costs an
    // extra name here because `D`'s constraint then has to be met by the
    // argument (`Flatten<…> & AnyVariant`). Written in the body the checker
    // resolves it during instantiation and there is no alias left to echo.
    //
    // **The length is the weaker half**: 1.58× is thin by the 2–20×
    // standard, so the categorical half is checked too.
    const rendered = assertHoverBudget(app.compilation, {
      name: 'SafeResult',
      max: SAFE_RESULT_BUDGET,
    })

    for (const tag of DECLARED_TAGS) expect(rendered).toContain(`"${tag}"`)
    expect(rendered).toContain('requiredRole')
    expect(rendered).not.toContain('SerializeObject')
    // And the success arm is Nitro's own success type beside it, untouched.
    expect(rendered).toContain('ok: true')
    expect(rendered).toContain('email: string')
  })

  it('renders `.safe`’s false arm as the flat variant union', () => {
    // The hover a caller consults while writing the `switch` — the flat variant
    // union, reached through `.safe` rather than through the reader — which is
    // the point of the false arm carrying the variant rather than the envelope:
    // there is nothing to unwrap and no `| undefined` in the way.
    const rendered = app.compilation.renderHover('SafeError')

    for (const tag of DECLARED_TAGS) expect(rendered).toContain(`"${tag}"`)
    expect(rendered).toContain('requiredRole')
    expect(rendered).not.toContain('SerializeObject')
    expect(rendered).not.toContain('undefined')
  })

  it('collapses an undeclared route’s `.safe` result to one arm', () => {
    // The degradation collapse on this surface, and it is mandatory
    // for a *different* reason than the composable needed it: a union member
    // whose property is `never` is not itself `never`, so without it `ok` stays
    // `boolean` and `data` is unreachable without a branch that can never be
    // taken. `/api/boom` is a plain `defineEventHandler` in this real app.
    expect(app.compilation.renderHover('UndeclaredSafeOk')).toBe('true')
  })

  it('leaves the throwing form byte-identical to vanilla, in a real app', () => {
    // The default entry point adds typings only, where `MatchedRoutes` has this
    // app's real keys to score rather than none.
    expect(app.compilation.renderHover('TypedThrown')).toBe(
      app.compilation.renderHover('VanillaThrown')
    )
  })

  it('answers `never` for a key the map holds and Nitro’s does not', () => {
    // The convergence window, one layer up from `Ghost` below: the
    // unreachable key degrades to the documented silent default rather than
    // to the union the map is holding for it.
    expect(app.compilation.renderHover('LookupGhost')).toBe('never')
  })

  it('cannot answer for a route whose handler resolves to nothing', () => {
    // The island-renderer case, recorded as a measurement rather than inherited
    // as a warning. Nuxt registers its island renderer as
    // `#internal/nuxt/island-renderer`; `resolveNitroPath` does not resolve that
    // alias, so the emitter faithfully writes a specifier pointing at no file
    // and the entry becomes TypeScript's error type — which `MatchedRoutes`
    // reaches, and which no `IsAny` guard can see. The only fix would
    // be a filesystem read inside the pure emitter, which its purity forbids.
    //
    // Asserted here so that the day it *stops* being true — Nuxt resolving the
    // alias, or the emitter learning to skip such handlers — is a visible
    // change rather than a silent one.
    expect(() => app.compilation.renderHover('LookupIsland')).toThrow(
      /rendered as `any`/
    )
  })

  it('holds a key Nitro’s interface does not, unreachably', () => {
    // The dev-server race, asserted structurally rather than statistically. The
    // probe declares `/api/ghost` on the map and nothing declares it on
    // `InternalApi` — the shape the convergence window produces — and
    // `MatchedRoutes` derives its key universe from `keyof InternalApi`, so the
    // key is unreachable by construction. That is why the race measurement
    // recorded `misattributed: 0` rather than merely "few", and why no guard
    // machinery ships. `pnpm dev-race` is where the clock gets watched.
    //
    // The same claim is made hermetically in
    // `test/types/unreachable-map-key.test.ts`. Re-taken here because this
    // program resolves it against the app's **real generated `InternalApi`**
    // rather than a hand-written stand-in, and the program was already built.
    expect(app.compilation.renderHover('Ghost')).toBe('never')
  })
})

describe('event.$typedFetch, in the real server program', () => {
  /**
   * The same built app, compiled a second time through its generated
   * `tsconfig.server.json`. Everything above ran in the app program; this is
   * the program a handler author's `event.$typedFetch` call site is actually
   * typed in, and the README gap this block closes is precisely that no
   * rendering assertion had ever been taken through it.
   */
  let server: Compilation

  beforeAll(() => {
    server = probeServerApp(app.root)
  }, 600_000)

  it('compiles the server probe clean, with the map in the program', () => {
    // The clean-program assertion for this program, and the license for the render
    // below: a hover out of a program that did not compile clean is a guess.
    assertNoDiagnostics(server)
  })

  it('renders `.safe`’s result flat, in budget, with the callee’s real tags', () => {
    // The flat-render mandate taken through `event.$typedFetch` — the hover a handler
    // author lands on first, on the surface whose whole point is being called
    // from other handlers. The tags are the resolution half:
    // the map entry's handler specifier resolved from *this* program, or the
    // harness would have refused the render as `any`.
    const rendered = assertHoverBudget(server, {
      name: 'EventSafeResult',
      max: EVENT_SAFE_RESULT_BUDGET,
    })

    for (const tag of DECLARED_TAGS) expect(rendered).toContain(`"${tag}"`)
    expect(rendered).toContain('requiredRole')
    expect(rendered).not.toContain('SerializeObject')
    // And the success arm is Nitro's own success type beside it, untouched.
    expect(rendered).toContain('ok: true')
    expect(rendered).toContain('email: string')
  })
})

describe('the lookup, over a map whose specifiers resolve to nothing', () => {
  /**
   * The mutation that makes every rendering assertion above worth writing.
   *
   * The same real build, with one thing changed: every handler specifier in the
   * emitted map now points at a directory that is not there. That is what
   * emitting the file outside Nitro's `types/` directory does, and what
   * `pathe.relative` returning a bare name does — both of them silent, because
   * an unresolved `import("…")` inside a `.d.ts` produces **no diagnostic**
   * under `skipLibCheck`, which every Nuxt-generated tsconfig sets.
   *
   * The two `it`s below are
   * taken at the *lookup* rather than at the raw map entry: the structural
   * assertions in the probe stay green while being false, and only the render
   * catches it.
   */
  let broken: BuiltApp

  beforeAll(() => {
    broken = probeApp(ensureBrokenFork(app, 'broken-specifiers'))
  }, 600_000)

  it('is swallowed whole: the probe’s own assertions stay green', () => {
    // `Lookup['tag']` is asserted to be three specific tags, and `Lookup` is
    // asserted equal to the raw map entry. Neither is true of this map — the
    // entry is TypeScript's error type, which propagates through every
    // conditional in `DeclaredErrorsOf` and satisfies whatever it meets. This
    // is what a suite looks like the day the emitter starts writing paths that
    // resolve to nothing, and it is why the claims that matter are renders.
    expect(
      broken.compilation.diagnostics.filter(
        (diagnostic) => diagnostic.fileName === broken.compilation.fixture
      )
    ).toEqual([])
  })

  it('is caught by the rendering assertion, which is why one is used', () => {
    expect(() => broken.compilation.renderHover('Lookup')).toThrow(
      /rendered as `any`/
    )
    expect(() => broken.compilation.renderHover('LookupFallback')).toThrow(
      /rendered as `any`/
    )
  })

  it('and the route matching is untouched, so the failure is localised', () => {
    // The control. `MatchedRoutes` reads `keyof InternalApi`, which no broken
    // handler specifier can affect — so a `never` from the lookup still means
    // "no such key" here, and the two failure modes stay distinguishable.
    expect(broken.compilation.renderHover('LookupGhost')).toBe('never')
  })
})

describe('path-referentiality, in a real Nuxt app', () => {
  /** The same app with one variant added to a catalogue. No route changes. */
  let edited: BuiltApp

  beforeAll(() => {
    edited = probeApp(
      ensureBuiltTree('content-edit', (root) => {
        const path = join(root, 'server/errors/user.ts')

        writeFileSync(
          path,
          readFileSync(path, 'utf8').replace(
            "  'user-suspended'",
            [
              `  'user-rate-limited': { status: 429, payload: payload<{ retryAfter: number }>() },`,
              `  'user-suspended'`,
            ].join('\n')
          )
        )
      })
    )
  }, 600_000)

  it('leaves the emitted file byte-identical after a content-only edit', () => {
    // The path-referentiality mandate, in the real app rather than only in the
    // pure function. Nitro never re-runs `writeTypes` on a `change` event and gets
    // away with it only because its output is an import expression the compiler
    // re-resolves on every edit; anything that resolved *values* at emit time
    // would go stale here with no watcher that would ever fix it.
    expect(edited.map).toBe(app.map)
  })

  it('and the compiler sees the new variant anyway', () => {
    // The other half, and the half a byte comparison cannot make: identical
    // output would be worthless if the type were stale too.
    const rendered = edited.compilation.renderHover('Declared')

    expect(rendered).toContain('"user-rate-limited"')
    expect(rendered).toContain('retryAfter')
  })
})
