import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { beforeAll, describe, expect, it } from 'vitest'
import { EMPTY_MAP, TYPES_SPECIFIER } from '../../src/emit-map'

/**
 * The map, produced by a **real Nuxt build** rather than by calling the
 * emitter.
 *
 * This is the layer nothing else substitutes for: every other assertion in the
 * package runs against handler records written by hand, and only this one
 * catches the type-generation hook silently ceasing to fire — the single most
 * likely thing a Nuxt or Nitro patch release breaks.
 *
 * `nuxt prepare` rather than a full build: `types:extend` fires inside Nitro's
 * `writeTypes`, which is exactly what `prepare` runs.
 *
 * The claims here are **structural** — the file exists, where it must exist,
 * keyed as Nitro keys, reachable from all three programs. That the emitted
 * text *resolves* is asserted in `test/types/emitted-map.test.ts`, which
 * compiles it and renders the union back out. The rendering half taken through
 * a real app (and the hover budgets that go with it) waits on the playground.
 */

const PACKAGE_ROOT = fileURLToPath(new URL('../..', import.meta.url))
const FIXTURE = join(PACKAGE_ROOT, 'test/fixtures/basic')

/**
 * Where the map must land: Nitro's `typesDir` is `resolve(buildDir, 'types')`,
 * and Nuxt hands Nitro its own `buildDir`.
 *
 * Written out rather than imported from `src/module.ts`. That is the point —
 * the emitter computes every specifier relative to this directory, so a test
 * that took the path from the code under test would follow the file wherever
 * it moved and stay green.
 */
const MAP_PATH = join('.nuxt', 'types', 'nuxt-handler-errors.d.ts')

/** The generated tsconfigs the hoist entry has to reach: app, server, shared. */
const GENERATED_TSCONFIGS = [
  'tsconfig.json',
  'tsconfig.server.json',
  'tsconfig.shared.json',
]

/**
 * The `/// <reference>` each context reaches the map through, and the
 * `addTypeTemplate` flag that puts it there.
 *
 * Naming the flag beside the file is the point: the obvious snippet passes
 * `{ nitro: true }`, which buys the third row and silently drops the other two.
 */
const CONTEXT_REFERENCES = [
  { flag: 'nuxt', file: join('.nuxt', 'nuxt.d.ts') },
  { flag: 'shared', file: join('.nuxt', 'nuxt.shared.d.ts') },
  { flag: 'nitro', file: join('.nuxt', 'types', 'nitro-nuxt.d.ts') },
]

/**
 * An emitted map with its route blocks removed — the banner, the two imports,
 * the `declare module` wrapper and the closing `export {}`.
 *
 * Route blocks are the only lines the emitter indents four spaces, which is
 * why that is the filter.
 */
function fileShell(source: string): string {
  return source
    .split('\n')
    .filter((line) => !line.startsWith('    '))
    .join('\n')
}

let map: string

beforeAll(() => {
  execFileSync(
    join(PACKAGE_ROOT, 'node_modules/.bin/nuxt'),
    ['prepare', FIXTURE],
    { cwd: PACKAGE_ROOT, stdio: 'pipe' }
  )

  const mapPath = join(FIXTURE, MAP_PATH)
  if (!existsSync(mapPath)) {
    throw new Error(
      [
        `\`nuxt prepare\` produced no map at ${MAP_PATH}.`,
        'Either the type template was never registered, or it was emitted',
        "somewhere other than Nitro's types directory — where every specifier",
        'in it would resolve to nothing, silently.',
      ].join('\n')
    )
  }

  map = readFileSync(mapPath, 'utf8')
}, 300_000)

describe('the generated map, in a real Nuxt app', () => {
  it('lands in Nitro’s own types directory, under the build directory', () => {
    // The `beforeAll` throws if it is not there, so this records what the file
    // is. The directory is not a preference: every specifier in the file is
    // relative to it, and moving the file one level up leaves the whole map
    // resolving to nothing with no diagnostic anywhere.
    expect(map).toContain('Generated by @dphonys/nuxt-handler-errors')
  })

  it('seeds a cold start with the same file shell it later replaces', () => {
    // `nuxi dev` races `writeTypes` against `buildNuxt`, so the template can be
    // asked for its contents before `nitro:init` has fired, and a
    // `/// <reference>` to a file that is not a module is a dangling one.
    //
    // This holds by construction — `EMPTY_MAP` is the emitter's own
    // `renderFile` applied to no routes — and saying so is the point: the
    // regression it guards against is the seed being spelled a second time.
    expect(fileShell(EMPTY_MAP)).toBe(fileShell(map))
  })

  it('keys every route the app serves, and keys them as Nitro does', () => {
    expect(map).toContain(`    '/api/users/:id': {`)
    expect(map).toContain(`    '/api/legacy': {`)

    // Nitro's own `[id]` → `:id` rewrite and its own extension stripping,
    // arrived at by re-running Nitro's loop rather than reimplementing it.
    expect(map).toContain(
      `typeof import('../../server/api/users/[id].get').default`
    )
  })

  it('augments the module’s own specifier, and closes as a module', () => {
    // Never Nitro's namespace: a future Nitro release owning this name would
    // break consumers silently, and `KnownApiErrors` appears in every wrapper
    // signature, so declaring it there would hand this module's public surface
    // a second owner.
    expect(map).toContain(`declare module '${TYPES_SPECIFIER}' {`)
    expect(map).not.toContain(`declare module 'nitropack/types'`)
    expect(map.trimEnd().endsWith('export {}')).toBe(true)
  })

  it('is hoisted onto every generated tsconfig', () => {
    // A load-bearing string, asserted through its effect. Removing
    // `typescript.hoist.push(…)` empties all three of these.
    for (const config of GENERATED_TSCONFIGS) {
      expect(readFileSync(join(FIXTURE, '.nuxt', config), 'utf8')).toContain(
        `"${TYPES_SPECIFIER}"`
      )
    }
  })

  it('is referenced from the app, shared and server programs', () => {
    for (const { flag, file } of CONTEXT_REFERENCES) {
      expect(
        readFileSync(join(FIXTURE, file), 'utf8'),
        `addTypeTemplate({ …, ${flag}: true }) should have written ${file}`
      ).toContain('nuxt-handler-errors.d.ts')
    }
  })
})
