import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { beforeAll, describe, expect, it } from 'vitest'
import { EMPTY_MAP, TYPES_SPECIFIER } from '../../src/emit-map'

// The map, produced by a real Nuxt build. This is the only layer that catches
// the type-generation hook silently ceasing to fire. `nuxt prepare` rather
// than a full build: `types:extend` fires inside Nitro's `writeTypes`, which
// is exactly what `prepare` runs. The claims here are structural; that the
// emitted text *resolves* is `test/types/emitted-map.test.ts`'s job.

const PACKAGE_ROOT = fileURLToPath(new URL('../..', import.meta.url))
const FIXTURE = join(PACKAGE_ROOT, 'test/fixtures/basic')

// Where the map must land: Nitro's `typesDir`. Written out rather than
// imported from `src/module.ts` — a test that took the path from the code
// under test would follow the file wherever it moved and stay green.
const MAP_PATH = join('.nuxt', 'types', 'nuxt-handler-errors.d.ts')

/** The generated tsconfigs the hoist entry has to reach: app, server, shared. */
const GENERATED_TSCONFIGS = [
  'tsconfig.json',
  'tsconfig.server.json',
  'tsconfig.shared.json',
]

// The `/// <reference>` each context reaches the map through, and the
// `addTypeTemplate` flag that puts it there — the obvious `{ nitro: true }`
// buys only the third row.
const CONTEXT_REFERENCES = [
  { flag: 'nuxt', file: join('.nuxt', 'nuxt.d.ts') },
  { flag: 'shared', file: join('.nuxt', 'nuxt.shared.d.ts') },
  { flag: 'nitro', file: join('.nuxt', 'types', 'nitro-nuxt.d.ts') },
]

/**
 * An emitted map with its route blocks removed. Route blocks are the only
 * lines the emitter indents four spaces.
 */
function fileShell(source: string): string {
  return source
    .split('\n')
    .filter((line) => !line.startsWith('    '))
    .join('\n')
}

let map: string

beforeAll(() => {
  execFileSync(
    join(PACKAGE_ROOT, 'node_modules/.bin/nuxt'),
    ['prepare', FIXTURE],
    { cwd: PACKAGE_ROOT, stdio: 'pipe' }
  )

  const mapPath = join(FIXTURE, MAP_PATH)
  if (!existsSync(mapPath)) {
    throw new Error(
      [
        `\`nuxt prepare\` produced no map at ${MAP_PATH}.`,
        'Either the type template was never registered, or it was emitted',
        "somewhere other than Nitro's types directory — where every specifier",
        'in it would resolve to nothing, silently.',
      ].join('\n')
    )
  }

  map = readFileSync(mapPath, 'utf8')
}, 300_000)

describe('the generated map, in a real Nuxt app', () => {
  it('lands in Nitro’s own types directory, under the build directory', () => {
    // Every specifier in the file is relative to that directory; moving the
    // file one level up leaves the whole map resolving to nothing.
    expect(map).toContain('Generated by @dphonys/nuxt-handler-errors')
  })

  it('seeds a cold start with the same file shell it later replaces', () => {
    // `nuxi dev` races `writeTypes` against `buildNuxt`, so the template can
    // be asked for its contents before `nitro:init` has fired. `EMPTY_MAP` is
    // the emitter's own render of no routes; the regression guarded against
    // is the seed being spelled a second time.
    expect(fileShell(EMPTY_MAP)).toBe(fileShell(map))
  })

  it('keys every route the app serves, and keys them as Nitro does', () => {
    expect(map).toContain(`    '/api/users/:id': {`)
    expect(map).toContain(`    '/api/legacy': {`)

    // Nitro's own `[id]` → `:id` rewrite and extension stripping.
    expect(map).toContain(
      `typeof import('../../server/api/users/[id].get').default`
    )
  })

  it('augments the module’s own specifier, and closes as a module', () => {
    // Never Nitro's namespace: a future Nitro release owning this name would
    // break consumers silently.
    expect(map).toContain(`declare module '${TYPES_SPECIFIER}' {`)
    expect(map).not.toContain(`declare module 'nitropack/types'`)
    expect(map.trimEnd().endsWith('export {}')).toBe(true)
  })

  it('is hoisted onto every generated tsconfig', () => {
    // Removing `typescript.hoist.push(…)` empties all three of these.
    for (const config of GENERATED_TSCONFIGS) {
      expect(readFileSync(join(FIXTURE, '.nuxt', config), 'utf8')).toContain(
        `"${TYPES_SPECIFIER}"`
      )
    }
  })

  it('is referenced from the app, shared and server programs', () => {
    for (const { flag, file } of CONTEXT_REFERENCES) {
      expect(
        readFileSync(join(FIXTURE, file), 'utf8'),
        `addTypeTemplate({ …, ${flag}: true }) should have written ${file}`
      ).toContain('nuxt-handler-errors.d.ts')
    }
  })
})
