import type { NitroEventHandler } from 'nitropack/types'
import { describe, expect, it } from 'vitest'
import { emitMap, TYPES_SPECIFIER } from '../../src/emit-map'
import type { NitroPathOptions } from '../../src/emit-map'

// The emitter as a pure function — string comparisons only. Whether the
// emitted text *resolves* is asserted in `test/types/emitted-map.test.ts`,
// which compiles it: a broken `import("…")` in a `.d.ts` produces no
// diagnostic under `skipLibCheck` and collapses silently to `any`.

/** A Nuxt-shaped Nitro: `srcDir` is `<rootDir>/server`, `buildDir` is `.nuxt`. */
const NITRO: NitroPathOptions = {
  buildDir: '/app/.nuxt',
  srcDir: '/app/server',
  alias: { '~': '/app', '@': '/app', '~~': '/app' },
}

/** The whole `Simplify<Serialize<KnownErrorsOfHandler<…>>>` wrapper, spelled once. */
function declared(specifier: string): string {
  return `Simplify<Serialize<KnownErrorsOfHandler<typeof import('${specifier}').default>>>`
}

/** The `'<method>': …` line a route+method entry renders as. */
function entryLine(method: string, ...specifiers: string[]): string {
  return `      '${method}': ${specifiers.map(declared).join(' | ')}`
}

describe('the generated map’s frame', () => {
  const emitted = emitMap(
    [
      {
        route: '/api/boom',
        method: 'get',
        handler: '/app/server/api/boom.get.ts',
      },
    ],
    { nitroOptions: NITRO }
  )

  it('augments the module’s own specifier and imports the extractor from it', () => {
    // Literals rather than interpolated from the constant, so renaming the
    // constant cannot quietly rewrite the assertion too.
    expect(emitted).toContain(
      `import type { KnownErrorsOfHandler } from '@dphonys/nuxt-handler-errors/types'`
    )
    expect(emitted).toContain(
      `declare module '@dphonys/nuxt-handler-errors/types' {`
    )
    expect(TYPES_SPECIFIER).toBe('@dphonys/nuxt-handler-errors/types')
    expect(emitted).not.toContain(`declare module 'nitropack/types'`)
  })

  it('takes Serialize and Simplify from nitropack rather than copying them', () => {
    expect(emitted).toContain(
      `import type { Serialize, Simplify } from 'nitropack/types'`
    )
  })

  it('ends in an empty export, so the file is a module', () => {
    // Without it the file is ambient and the block above stops being an
    // augmentation.
    expect(emitted.trimEnd().endsWith('export {}')).toBe(true)
  })

  it('renders as a whole, readable declaration', () => {
    expect(emitted).toBe(
      [
        '// Generated by @dphonys/nuxt-handler-errors — do not edit',
        `import type { Serialize, Simplify } from 'nitropack/types'`,
        `import type { KnownErrorsOfHandler } from '@dphonys/nuxt-handler-errors/types'`,
        `declare module '@dphonys/nuxt-handler-errors/types' {`,
        '  interface KnownApiErrors {',
        `    '/api/boom': {`,
        entryLine('get', '../../server/api/boom.get'),
        '    }',
        '  }',
        '}',
        'export {}',
        '',
      ].join('\n')
    )
  })

  it('emits an empty interface when Nitro scanned nothing', () => {
    expect(emitMap([], { nitroOptions: NITRO })).toContain(
      '  interface KnownApiErrors {\n  }'
    )
  })
})

describe('route and method keys, re-derived from Nitro’s own arrays', () => {
  it('keys every route Nitro knows, branded or not', () => {
    // Keying every route makes the lookup total; an unbranded handler
    // extracts to `never` naturally, so the emitter has no notion of
    // "branded" at all.
    const emitted = emitMap(
      [
        {
          route: '/api/branded',
          method: 'get',
          handler: '/app/server/api/branded.get.ts',
        },
        {
          route: '/api/legacy',
          method: 'get',
          handler: '/app/server/api/legacy.get.js',
        },
      ],
      { nitroOptions: NITRO }
    )

    expect(emitted).toContain(`    '/api/branded': {`)
    expect(emitted).toContain(`    '/api/legacy': {`)
  })

  it('keeps Nitro’s parameter, catch-all and route-group route strings verbatim', () => {
    // The keys are Nitro's own `mw.route`, never re-derived from the filename.
    const emitted = emitMap(
      [
        {
          route: '/api/users/:id',
          method: 'get',
          handler: '/app/server/api/users/[id].get.ts',
        },
        {
          route: '/api/files/**:slug',
          handler: '/app/server/api/files/[...slug].ts',
        },
        { route: '/api/**', handler: '/app/server/api/[...].ts' },
        {
          route: '/health',
          method: 'get',
          handler: '/app/server/routes/(admin)/health.get.ts',
        },
      ],
      { nitroOptions: NITRO }
    )

    expect(emitted).toContain(`    '/api/users/:id': {`)
    expect(emitted).toContain(`    '/api/files/**:slug': {`)
    expect(emitted).toContain(`    '/api/**': {`)
    expect(emitted).toContain(`    '/health': {`)
    expect(emitted).toContain(declared('../../server/api/files/[...slug]'))
    expect(emitted).toContain(
      declared('../../server/routes/(admin)/health.get')
    )
  })

  it('files a handler with no method of its own under `default`', () => {
    const emitted = emitMap(
      [{ route: '/api/y', handler: '/app/server/api/y.ts' }],
      {
        nitroOptions: NITRO,
      }
    )

    expect(emitted).toContain(entryLine('default', '../../server/api/y'))
  })

  it('files an empty method under `default`, as Nitro’s `||` does', () => {
    // Nitro writes `mw.method || "default"`. `??` would file this under `''`
    // and the route would answer on no method at all.
    const emitted = emitMap(
      [
        {
          route: '/api/blank',
          method: '' as NonNullable<NitroEventHandler['method']>,
          handler: '/app/server/api/blank.ts',
        },
      ],
      { nitroOptions: NITRO }
    )

    expect(emitted).toContain(entryLine('default', '../../server/api/blank'))
    expect(emitted).not.toContain(`      '': `)
  })

  it('lowercases a method a module passed through unmodified', () => {
    // Filesystem scanning guarantees lowercase; `addServerHandler` does not,
    // and modules hand it `'POST'`. The lookup side normalises with
    // `Lowercase<M>`, so an uppercased key here would never be found.
    const emitted = emitMap(
      [
        {
          route: '/api/programmatic',
          method: 'POST' as NonNullable<NitroEventHandler['method']>,
          handler: '/app/server/api/programmatic.ts',
        },
      ],
      { nitroOptions: NITRO }
    )

    expect(emitted).toContain(
      entryLine('post', '../../server/api/programmatic')
    )
    expect(emitted).not.toContain(`'POST'`)
  })

  it('unions multiple handlers on one route and method, in Nitro’s order', () => {
    const emitted = emitMap(
      [
        {
          route: '/api/dup',
          method: 'get',
          handler: '/app/server/api/dup.get.ts',
        },
        {
          route: '/api/dup',
          method: 'get',
          handler: '/app/modules/extra/dup.get.ts',
        },
      ],
      { nitroOptions: NITRO }
    )

    expect(emitted).toContain(
      entryLine(
        'get',
        '../../server/api/dup.get',
        '../../modules/extra/dup.get'
      )
    )
  })

  it('keeps a route’s methods apart, including alongside a default', () => {
    const emitted = emitMap(
      [
        { route: '/api/y', handler: '/app/server/api/y.ts' },
        {
          route: '/api/y',
          method: 'post',
          handler: '/app/server/api/y.post.ts',
        },
      ],
      { nitroOptions: NITRO }
    )

    expect(emitted).toContain(entryLine('default', '../../server/api/y'))
    expect(emitted).toContain(entryLine('post', '../../server/api/y.post'))
  })

  it('skips middleware and any handler that is not a path', () => {
    // Nitro's own guard: a route-less entry is middleware, and a dev handler
    // carries a function rather than a path.
    const emitted = emitMap(
      [
        {
          route: '',
          handler: '/app/server/middleware/auth.ts',
          middleware: true,
        },
        {
          route: '/api/live',
          handler: (() => {}) as unknown as string,
        },
        {
          route: '/api/real',
          method: 'get',
          handler: '/app/server/api/real.get.ts',
        },
      ],
      { nitroOptions: NITRO }
    )

    expect(emitted).not.toContain('middleware/auth')
    expect(emitted).not.toContain(`'/api/live'`)
    expect(emitted).toContain(`    '/api/real': {`)
  })

  it('is a function of the route set, not of the order the arrays were concatenated', () => {
    const scanned: NitroEventHandler = {
      route: '/api/a',
      method: 'get',
      handler: '/app/server/api/a.get.ts',
    }
    const configured: NitroEventHandler = {
      route: '/api/b',
      method: 'get',
      handler: '/app/server/api/b.get.ts',
    }

    expect(emitMap([scanned, configured], { nitroOptions: NITRO })).toBe(
      emitMap([configured, scanned], { nitroOptions: NITRO })
    )
  })
})

/** The module specifier the emitter writes for one handler path. */
function specifierFor(
  handlerPath: string,
  nitro: NitroPathOptions = NITRO
): string {
  const emitted = emitMap(
    [{ route: '/r', method: 'get', handler: handlerPath }],
    { nitroOptions: nitro }
  )
  const match = /import\('([^']*)'\)/.exec(emitted)

  if (match?.[1] === undefined) {
    throw new Error(`No import specifier in:\n${emitted}`)
  }

  return match[1]
}

describe('relative handler specifiers', () => {
  it('walks out of the types directory to a nested route file', () => {
    expect(specifierFor('/app/server/api/users/[id].get.ts')).toBe(
      '../../server/api/users/[id].get'
    )
  })

  it('reaches a handler that lives outside the Nuxt root entirely', () => {
    // A Nuxt layer, a workspace package, or `addServerHandler` pointing at a
    // module's own `runtime/` — none are under `srcDir`.
    expect(
      specifierFor('/workspace/layers/base/server/api/shared.get.ts')
    ).toBe('../../../workspace/layers/base/server/api/shared.get')
  })

  it('forces `./` on a handler that resolves into the types directory itself', () => {
    // `pathe.relative` returns a bare name for a sibling, and a bare
    // specifier in a `.d.ts` is a *package* name — it resolves to nothing,
    // silently, under `skipLibCheck`.
    expect(specifierFor('/app/.nuxt/types/generated.get.ts')).toBe(
      './generated.get'
    )
  })

  it('forces `./` on a dot-directory sibling, which is not a relative specifier either', () => {
    expect(specifierFor('/app/.nuxt/types/.generated/route.get.ts')).toBe(
      './.generated/route.get'
    )
  })

  it('leaves an absolute result absolute rather than prefixing `./`', () => {
    // Another Windows drive is the one input `relative` cannot express
    // relatively: `./D:/…` is a bare specifier, while the absolute path
    // resolves.
    const specifier = specifierFor(
      'D:\\layers\\base\\server\\api\\far.get.ts',
      {
        buildDir: 'C:\\app\\.nuxt',
        srcDir: 'C:\\app\\server',
        alias: {},
      }
    )

    expect(specifier).toBe('D:/layers/base/server/api/far.get')
    expect(specifier).not.toContain('./D:')
  })

  it('resolves Nitro’s aliases through Nitro’s own resolver', () => {
    expect(specifierFor('~/server/api/aliased.get.ts')).toBe(
      '../../server/api/aliased.get'
    )
  })

  it('resolves a bare relative handler against srcDir, as Nitro does', () => {
    expect(specifierFor('api/loose.get.ts')).toBe('../../server/api/loose.get')
  })

  it('emits POSIX separators for Windows inputs', () => {
    // A backslash in an emitted module specifier is an escape sequence, not a
    // separator.
    const specifier = specifierFor('C:\\app\\server\\api\\win.get.ts', {
      buildDir: 'C:\\app\\.nuxt',
      srcDir: 'C:\\app\\server',
      alias: {},
    })

    expect(specifier).toBe('../../server/api/win.get')
    expect(specifier).not.toContain('\\')
  })

  it('strips exactly the extensions Nitro strips', () => {
    for (const extension of [
      'js',
      'mjs',
      'cjs',
      'ts',
      'mts',
      'cts',
      'tsx',
      'jsx',
    ]) {
      expect(specifierFor(`/app/server/api/r.get.${extension}`)).toBe(
        '../../server/api/r.get'
      )
    }
  })

  it('leaves a dotted directory name alone', () => {
    // The strip is end-anchored, so `v1.2` in a directory is not an extension.
    expect(specifierFor('/app/server/api/v1.2/r.get.ts')).toBe(
      '../../server/api/v1.2/r.get'
    )
  })

  it('escapes a quote in a path rather than emitting broken TypeScript', () => {
    // Apostrophes are legal in file names; one unescaped would end the string
    // literal mid-specifier.
    expect(
      emitMap([{ route: `/it's`, handler: `/app/server/routes/it's.ts` }], {
        nitroOptions: NITRO,
      })
    ).toContain(`    '/it\\'s': {`)
  })

  it('escapes a line terminator, which would not end the literal but unterminate it', () => {
    // A newline is legal in a POSIX file name; unescaped it is an
    // unterminated string literal, so the whole generated `.d.ts` stops
    // parsing and every route goes with it.
    const emitted = emitMap(
      [
        { route: '/we\nird', handler: '/app/server/routes/we\nird.ts' },
        { route: '/re\rturn', handler: '/app/server/routes/re\rturn.ts' },
        {
          route: '/sep\u2028arator',
          handler: '/app/server/routes/sep\u2028arator.ts',
        },
        {
          route: '/para\u2029graph',
          handler: '/app/server/routes/para\u2029graph.ts',
        },
      ],
      { nitroOptions: NITRO }
    )

    expect(emitted).toContain(`    '/we\\nird': {`)
    expect(emitted).toContain(`    '/re\\rturn': {`)
    expect(emitted).toContain(`    '/sep\\u2028arator': {`)
    expect(emitted).toContain(`    '/para\\u2029graph': {`)

    // Every literal the file opens, it closes on the same line: a raw `\n`
    // in a route key would split one entry across two lines.
    expect(
      emitted.split('\n').filter((line) => /^ {4}'/.test(line))
    ).toHaveLength(4)
    expect(emitted).not.toMatch(/[\r\u2028\u2029]/)
  })
})

describe('path-referentiality', () => {
  it('is blind to catalogue content: only routes and paths reach the output', () => {
    // Nitro never regenerates route types on a content change; its output
    // survives only because it is an import expression the compiler
    // re-resolves on every edit. Anything resolving values at emit time would
    // go stale with no watcher to fix it. Asserted structurally here, and
    // against two real trees in `test/types/emitted-map.test.ts`.
    const routes: NitroEventHandler[] = [
      {
        route: '/api/users/:id',
        method: 'get',
        handler: '/app/server/api/users/[id].get.ts',
      },
      {
        route: '/api/boom',
        method: 'get',
        handler: '/app/server/api/boom.get.ts',
      },
    ]

    expect(emitMap(routes, { nitroOptions: NITRO })).toBe(
      emitMap(routes, { nitroOptions: NITRO })
    )
    expect(emitMap(routes, { nitroOptions: NITRO })).not.toContain('tag')
    expect(emitMap(routes, { nitroOptions: NITRO })).not.toContain('status')
  })
})
