import { describe, expect, it } from 'vitest'
import { typeMap } from '../../src/build/type-map'

// The generated file's own claims, made without a Nuxt build: where it lands,
// and what a cold start reads before Nitro exists. The parents' emitter is
// tested next door in its own package; what is asserted here is that this
// module asks it for *both* slots - the seed is the one state no route
// exercises, and the parent's own `EMPTY_MAP` (one slot) would pass every
// structural check an app makes.

const MAP = typeMap('nuxt-typed-handler')

/** The two interfaces the file carries, and the specifier each augments. */
const SLOTS = [
  {
    specifier: '@dphonys/nuxt-handler-errors/types',
    interfaceName: 'KnownApiErrors',
  },
  {
    specifier: '@dphonys/nuxt-typed-handler/types',
    interfaceName: 'KnownApiRequestInputs',
  },
]

describe('the generated map', () => {
  it('lands in Nitro’s own types directory, named for the module', () => {
    // Every specifier the emitter computes is relative to that directory.
    expect(MAP.filename).toBe('types/nuxt-typed-handler.d.ts')
  })

  it('seeds a cold start with one empty interface per slot', () => {
    // `nuxi dev` races `writeTypes` against `buildNuxt`, so the template can
    // be asked for its contents before `nitro:init` has fired.
    for (const { specifier, interfaceName } of SLOTS) {
      expect(MAP.empty).toContain(`declare module '${specifier}' {`)
      expect(MAP.empty).toContain(`interface ${interfaceName} {\n  }`)
    }

    expect(MAP.empty).toContain(
      '// Generated by nuxt-typed-handler - do not edit'
    )
    // A module, so the blocks above augment their interfaces rather than
    // declaring fresh global ones.
    expect(MAP.empty.trimEnd().endsWith('export {}')).toBe(true)
  })

  it('replaces the seed with the same file shell, filled in', () => {
    // Route blocks are the only lines the emitter indents four spaces, so
    // dropping them leaves exactly the shell the seed already wrote.
    const emitted = MAP.emit(
      [{ route: '/api/x', method: 'get', handler: '/app/server/api/x.get.ts' }],
      { buildDir: '/app/.nuxt', srcDir: '/app/server', alias: {} }
    )

    expect(shellOf(emitted)).toBe(shellOf(MAP.empty))
    expect(emitted).toContain(`    '/api/x': {`)
  })
})

/** An emitted map with its route blocks removed. */
function shellOf(source: string): string {
  return source
    .split('\n')
    .filter((line) => !line.startsWith('    '))
    .join('\n')
}
