// The emitter: the generated route → declared-errors map as a pure
// `(handlers, options) => string`. The text is a function of routes and
// handler PATHS, never definition content — anything resolving values at emit
// time goes stale with no watcher that would fix it.

import { resolveNitroPath } from 'nitropack/kit'
import type { Nitro, NitroEventHandler } from 'nitropack/types'
import { isAbsolute, relative, resolve } from 'pathe'

/**
 * The specifier the map augments — the module's own name, not Nitro's.
 * Exported so `setup()`'s `typescript.hoist.push(...)` cannot drift from the
 * string actually emitted.
 */
export const TYPES_SPECIFIER = '@dphonys/nuxt-handler-errors/types'

const DEFAULT_METHOD = 'default'

// Nitro's own extension list, verbatim — kept identical or the stripped
// specifier disagrees with the one Nitro writes into `nitro-routes.d.ts`.
const SOURCE_EXTENSION = /\.(?:js|mjs|cjs|ts|mts|cts|tsx|jsx)$/

const RELATIVE_SPECIFIER = /^\.\.?\//

// Escaping, not rejection: a route key is a file name and must reach the map
// verbatim or it stops matching Nitro's.
const STRING_ESCAPES: Readonly<Record<string, string>> = {
  '\\': '\\\\',
  "'": "\\'",
  '\n': '\\n',
  '\r': '\\r',
  '\u2028': '\\u2028',
  '\u2029': '\\u2029',
}

const NEEDS_ESCAPE = /[\\'\n\r\u2028\u2029]/g

/** The slice of `Nitro['options']` the path arithmetic reads. */
export type NitroPathOptions = Pick<
  Nitro['options'],
  'alias' | 'buildDir' | 'srcDir'
>

export interface EmitMapOptions {
  /** Nitro's resolved options — `nitro.options` from the `nitro:init` closure. */
  readonly nitroOptions: NitroPathOptions
}

/**
 * Render the generated map. Nitro's own route-types loop re-run, with three
 * divergences: method keys are lowercased, keys are sorted so the output is a
 * function of the route set, and relative specifiers are forced to start with
 * `./`. Every route Nitro knows is keyed — an unbranded handler extracts to
 * `never` naturally.
 */
export function emitMap(
  handlers: readonly NitroEventHandler[],
  options: EmitMapOptions
): string {
  const { nitroOptions } = options

  // Nitro's `typesDir` — the emitted file lands beside `nitro-routes.d.ts`.
  const typesDir = resolve(nitroOptions.buildDir, 'types')

  // A `Map` rather than an object literal: `__proto__` is a legal directory name.
  const routes = new Map<string, Map<string, string[]>>()

  for (const handler of handlers) {
    // Nitro's own guard: dev handlers carry a function, and a route-less
    // entry is middleware.
    if (typeof handler.handler !== 'string' || !handler.route) continue

    // `||`, not `??`, because Nitro writes `mw.method || "default"`.
    const method = (handler.method || DEFAULT_METHOD).toLowerCase()
    const methods = getOrCreate(routes, handler.route, () => new Map())
    const declared = getOrCreate(methods, method, () => [])

    declared.push(
      declaredUnionFor(specifierFor(handler.handler, typesDir, nitroOptions))
    )
  }

  return renderFile(
    sortedEntries(routes).map(([route, methods]) => renderRoute(route, methods))
  )
}

/**
 * The map a build writes before Nitro exists — the same file shell as a
 * populated map, so the two cannot drift.
 */
export const EMPTY_MAP: string = renderFile([])

function renderFile(routeBlocks: readonly string[]): string {
  return [
    '// Generated by @dphonys/nuxt-handler-errors — do not edit',
    `import type { Serialize, Simplify } from 'nitropack/types'`,
    `import type { KnownErrorsOfHandler } from ${quote(TYPES_SPECIFIER)}`,
    `declare module ${quote(TYPES_SPECIFIER)} {`,
    '  interface KnownApiErrors {',
    ...routeBlocks,
    '  }',
    '}',
    // Makes this a module, which makes the block above an augmentation of
    // `KnownApiErrors` rather than a fresh global one.
    'export {}',
    '',
  ].join('\n')
}

function renderRoute(
  route: string,
  methods: ReadonlyMap<string, readonly string[]>
): string {
  return [
    `    ${quote(route)}: {`,
    ...sortedEntries(methods).map(
      ([method, declared]) => `      ${quote(method)}: ${declared.join(' | ')}`
    ),
    '    }',
  ].join('\n')
}

// `Serialize` also closes the index-signature door: such a handler reaches
// `KnownErrorsOfHandler` as `unknown`, and `Serialize<unknown>` is `never`.
function declaredUnionFor(specifier: string): string {
  return `Simplify<Serialize<KnownErrorsOfHandler<typeof import(${quote(specifier)}).default>>>`
}

// `relative` is pathe's, so separators are POSIX. The one path it cannot
// relativise — another Windows drive — comes back absolute and is emitted
// as-is, which TypeScript does resolve; `./D:/…` would not.
function specifierFor(
  handlerPath: string,
  typesDir: string,
  nitroOptions: NitroPathOptions
): string {
  const resolved = resolveNitroPath(
    handlerPath,
    nitroOptions as Nitro['options']
  )
  const specifier = relative(typesDir, resolved).replace(SOURCE_EXTENSION, '')

  return RELATIVE_SPECIFIER.test(specifier) || isAbsolute(specifier)
    ? specifier
    : `./${specifier}`
}

function quote(value: string): string {
  return `'${value.replaceAll(NEEDS_ESCAPE, (char) => STRING_ESCAPES[char] ?? char)}'`
}

function getOrCreate<K, V>(map: Map<K, V>, key: K, create: () => V): V {
  const existing = map.get(key)
  if (existing !== undefined) return existing

  const created = create()
  map.set(key, created)

  return created
}

// Codepoint order rather than `localeCompare`: the output must be identical
// on every machine that builds the app.
function sortedEntries<V>(map: ReadonlyMap<string, V>): [string, V][] {
  return [...map].toSorted(([left], [right]) =>
    left < right ? -1 : left > right ? 1 : 0
  )
}
