// The emitter: the generated route → declared-errors map as a pure
// `(handlers, options) => string`. The text is a function of routes and
// handler PATHS, never definition content - anything resolving values at emit
// time goes stale with no watcher that would fix it.

import { resolveNitroPath } from 'nitropack/kit'
import type { Nitro, NitroEventHandler } from 'nitropack/types'
import { isAbsolute, relative, resolve } from 'pathe'

/**
 * The specifier the map augments - the module's own name, not Nitro's.
 * Exported so `setup()`'s `typescript.hoist.push(...)` cannot drift from the
 * string actually emitted.
 */
export const TYPES_SPECIFIER = '@dphonys/nuxt-handler-errors/types'

const GENERATED_BY = '@dphonys/nuxt-handler-errors'

const DEFAULT_METHOD = 'default'

// Nitro's own extension list, verbatim - kept identical or the stripped
// specifier disagrees with the one Nitro writes into `nitro-routes.d.ts`.
const SOURCE_EXTENSION = /\.(?:js|mjs|cjs|ts|mts|cts|tsx|jsx)$/

const RELATIVE_SPECIFIER = /^\.\.?\//

// Escaping, not rejection: a route key is a file name and must reach the map
// verbatim or it stops matching Nitro's.
const STRING_ESCAPES: Readonly<Record<string, string>> = {
  '\\': '\\\\',
  "'": "\\'",
  '\n': '\\n',
  '\r': '\\r',
  '\u2028': '\\u2028',
  '\u2029': '\\u2029',
}

const NEEDS_ESCAPE = /[\\'\n\r\u2028\u2029]/g

/** The slice of `Nitro['options']` the path arithmetic reads. */
export type NitroPathOptions = Pick<
  Nitro['options'],
  'alias' | 'buildDir' | 'srcDir'
>

/** One `declare module` block of the emitted file, as data. */
export interface EmitMapSlot {
  /** The interface the `declare module` block augments. */
  readonly interfaceName: string
  /** The specifier the block augments, e.g. the package's own `/types`. */
  readonly specifier: string
  /** Type-only imports the extractor expression needs, deduplicated on emit. */
  readonly imports: readonly SlotImport[]
  /** Renders the per-handler value from the `typeof import('…').default` text. */
  readonly extract: (handlerType: string) => string
}

/** One `import type { names } from 'from'` a slot's extractor leans on. */
export interface SlotImport {
  readonly names: readonly string[]
  readonly from: string
}

// `Serialize` also closes the index-signature door: such a handler reaches
// `KnownErrorsOfHandler` as `unknown`, and `Serialize<unknown>` is `never`.
export const KNOWN_ERRORS_SLOT: EmitMapSlot = {
  interfaceName: 'KnownApiErrors',
  specifier: TYPES_SPECIFIER,
  imports: [
    { names: ['Serialize', 'Simplify'], from: 'nitropack/types' },
    { names: ['KnownErrorsOfHandler'], from: TYPES_SPECIFIER },
  ],
  extract: (handlerType) =>
    `Simplify<Serialize<KnownErrorsOfHandler<${handlerType}>>>`,
}

export interface EmitMapOptions {
  /** Nitro's resolved options - `nitro.options` from the `nitro:init` closure. */
  readonly nitroOptions: NitroPathOptions
  /** Defaults to `[KNOWN_ERRORS_SLOT]`. One `declare module` block per slot, in order. */
  readonly slots?: readonly EmitMapSlot[]
  /** The `// Generated by …` banner name. Defaults to this package's name. */
  readonly generatedBy?: string
}

/**
 * Render the generated map. Nitro's own route-types loop re-run, with three
 * divergences: method keys are lowercased, keys are sorted so the output is a
 * function of the route set, and relative specifiers are forced to start with
 * `./`. Every route Nitro knows is keyed - an unbranded handler extracts to
 * `never` naturally.
 */
export function emitMap(
  handlers: readonly NitroEventHandler[],
  options: EmitMapOptions
): string {
  const { nitroOptions } = options

  // Nitro's `typesDir` - the emitted file lands beside `nitro-routes.d.ts`.
  const typesDir = resolve(nitroOptions.buildDir, 'types')

  // A `Map` rather than an object literal: `__proto__` is a legal directory name.
  const routes = new Map<string, Map<string, string[]>>()

  for (const handler of handlers) {
    // Nitro's own guard: dev handlers carry a function, and a route-less
    // entry is middleware.
    if (typeof handler.handler !== 'string' || !handler.route) continue

    // `||`, not `??`, because Nitro writes `mw.method || "default"`.
    const method = (handler.method || DEFAULT_METHOD).toLowerCase()
    const methods = getOrCreate(routes, handler.route, () => new Map())
    const handlerTypes = getOrCreate(methods, method, () => [])

    handlerTypes.push(
      handlerTypeFor(specifierFor(handler.handler, typesDir, nitroOptions))
    )
  }

  // Iterated, sorted and escaped once; each slot only supplies the extractor.
  const grid: RouteRow[] = sortedEntries(routes).map(([route, methods]) => [
    quote(route),
    sortedEntries(methods).map(([method, handlerTypes]) => [
      quote(method),
      handlerTypes,
    ]),
  ])

  return renderFile(grid, options)
}

/**
 * The map a build writes before Nitro exists - the same file shell as a
 * populated map, so the two cannot drift.
 */
export function emptyMap(
  options: Pick<EmitMapOptions, 'slots' | 'generatedBy'> = {}
): string {
  return renderFile([], options)
}

export const EMPTY_MAP: string = emptyMap()

/** One method of a route: its quoted key and the handler types it unions. */
type MethodRow = readonly [method: string, handlerTypes: readonly string[]]

/** One route of the grid: its quoted key, then its methods in order. */
type RouteRow = readonly [route: string, methods: readonly MethodRow[]]

function renderFile(
  grid: readonly RouteRow[],
  options: Pick<EmitMapOptions, 'slots' | 'generatedBy'>
): string {
  const slots = options.slots ?? [KNOWN_ERRORS_SLOT]

  return [
    `// Generated by ${options.generatedBy ?? GENERATED_BY} - do not edit`,
    ...renderImports(slots),
    ...slots.flatMap((slot) => renderSlot(slot, grid)),
    // Makes this a module, which makes the blocks above augmentations of
    // their interfaces rather than fresh global ones.
    'export {}',
    '',
  ].join('\n')
}

// One line per `from`, in first-seen order, names merged across slots and
// sorted - two slots leaning on `nitropack/types` share the line.
function renderImports(slots: readonly EmitMapSlot[]): string[] {
  const byModule = new Map<string, Set<string>>()

  for (const slot of slots) {
    for (const { names, from } of slot.imports) {
      const merged = getOrCreate(byModule, from, () => new Set())
      for (const name of names) merged.add(name)
    }
  }

  return [...byModule].map(
    ([from, names]) =>
      `import type { ${sorted(names).join(', ')} } from ${quote(from)}`
  )
}

function renderSlot(slot: EmitMapSlot, grid: readonly RouteRow[]): string[] {
  return [
    `declare module ${quote(slot.specifier)} {`,
    `  interface ${slot.interfaceName} {`,
    ...grid.map(([route, methods]) => renderRoute(route, methods, slot)),
    '  }',
    '}',
  ]
}

function renderRoute(
  route: string,
  methods: readonly MethodRow[],
  slot: EmitMapSlot
): string {
  return [
    `    ${route}: {`,
    ...methods.map(
      ([method, handlerTypes]) =>
        `      ${method}: ${handlerTypes.map(slot.extract).join(' | ')}`
    ),
    '    }',
  ].join('\n')
}

function handlerTypeFor(specifier: string): string {
  return `typeof import(${quote(specifier)}).default`
}

// `relative` is pathe's, so separators are POSIX. The one path it cannot
// relativise - another Windows drive - comes back absolute and is emitted
// as-is, which TypeScript does resolve; `./D:/…` would not.
function specifierFor(
  handlerPath: string,
  typesDir: string,
  nitroOptions: NitroPathOptions
): string {
  const resolved = resolveNitroPath(
    handlerPath,
    nitroOptions as Nitro['options']
  )
  const specifier = relative(typesDir, resolved).replace(SOURCE_EXTENSION, '')

  return RELATIVE_SPECIFIER.test(specifier) || isAbsolute(specifier)
    ? specifier
    : `./${specifier}`
}

function quote(value: string): string {
  return `'${value.replaceAll(NEEDS_ESCAPE, (char) => STRING_ESCAPES[char] ?? char)}'`
}

function getOrCreate<K, V>(map: Map<K, V>, key: K, create: () => V): V {
  const existing = map.get(key)
  if (existing !== undefined) return existing

  const created = create()
  map.set(key, created)

  return created
}

// Codepoint order rather than `localeCompare`: the output must be identical
// on every machine that builds the app.
function sortedEntries<V>(map: ReadonlyMap<string, V>): [string, V][] {
  return [...map].toSorted(([left], [right]) => compare(left, right))
}

function sorted(values: Iterable<string>): string[] {
  return [...values].toSorted(compare)
}

function compare(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0
}
