import { execFileSync } from 'node:child_process'
import {
  cpSync,
  existsSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import ts from 'typescript'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { EMPTY_MAP, TYPES_SPECIFIER } from '../src/emit-map'
import { assertNoDiagnostics, createTypeHarness } from './types/harness'
import type { Compilation } from './types/harness'

/**
 * Layer 3 (SPEC.md §9.1): the map, produced by a **real Nuxt build** rather
 * than by calling the emitter.
 *
 * This is the layer nothing else substitutes for. Every other assertion in this
 * package runs against handler records written by hand; only this one catches
 * the type-generation hook silently ceasing to fire, which is the single most
 * likely thing a Nuxt or Nitro patch release breaks.
 *
 * ## Why it runs against a copy of the playground
 *
 * The sources are the playground's, copied byte for byte — the app under test
 * is itself the e2e fixture. Two reasons for the copy, and neither of them is
 * fastidiousness:
 *
 * - SPEC.md §4.4's path-referentiality claim can only be made by **editing a
 *   catalogue and rebuilding**, and `test/specifiers.test.ts` boots a server out
 *   of the same directory. Mutating tracked sources under a sibling suite's feet
 *   is a race, and the alternative — serialising the whole suite — would slow
 *   every run to pay for one assertion.
 * - A copy makes this file independent of whether anything else ran
 *   `nuxt prepare` first, so a failure here is always about this ticket.
 *
 * `node_modules` is symlinked rather than copied, which is what keeps the copy a
 * real consumer: the module resolves through its published `exports` map and
 * every generated `paths` entry points back at the package's own `dist/`.
 *
 * ## Why the central assertion is a *rendering* one
 *
 * Declaration emit writes type references as `import("…")` type nodes. One that
 * does not resolve inside a `.d.ts` produces **no diagnostic** under
 * `skipLibCheck`, which every Nuxt-generated tsconfig sets: the entry becomes
 * TypeScript's error type, which renders as `any` but satisfies every
 * `Expect<Equal<…>>` and every `IsAny` check made against it
 * (SPEC-AMENDMENTS items 8 and 9). Measured for this ticket by emitting the map
 * one directory too high — the whole playground compiled clean apart from the
 * single *control-flow* assertion in `app.vue`. So the claim made here is that
 * the union **renders with this route's real tags**: the harness refuses to
 * render `any`, and that refusal is the check that bites.
 */

const PACKAGE_ROOT = fileURLToPath(new URL('..', import.meta.url))
const PLAYGROUND = join(PACKAGE_ROOT, 'playground')

/**
 * Where the map must land: Nitro's `typesDir` is `resolve(buildDir, 'types')`,
 * and Nuxt hands Nitro its own `buildDir`.
 *
 * Written out rather than imported from `src/module.ts`. That is the point —
 * the emitter computes every specifier relative to this directory, so a test
 * that took the path from the code under test would follow the file wherever it
 * moved and stay green. Restating it is what makes the "emitted one level too
 * high" mutation red.
 */
const MAP_PATH = join('.nuxt', 'types', 'nuxt-handler-errors.d.ts')

/** Build output and installed packages: regenerated by `prepare`, or symlinked. */
const NOT_COPIED = /[/\\](?:node_modules|\.nuxt|\.output|\.turbo|dist)$/

/** The generated tsconfigs the hoist entry has to reach: app, server, shared. */
const GENERATED_TSCONFIGS = [
  'tsconfig.json',
  'tsconfig.server.json',
  'tsconfig.shared.json',
]

/**
 * The `/// <reference>` each context reaches the map through, and the
 * `addTypeTemplate` flag that puts it there.
 *
 * Naming the flag beside the file is the point: SPEC.md §4.2's own snippet
 * passes `{ nitro: true }`, which buys the third row and silently drops the
 * other two.
 */
const CONTEXT_REFERENCES = [
  { flag: 'nuxt', file: join('.nuxt', 'nuxt.d.ts') },
  { flag: 'shared', file: join('.nuxt', 'nuxt.shared.d.ts') },
  { flag: 'nitro', file: join('.nuxt', 'types', 'nitro-nuxt.d.ts') },
]

/** Every `/api` route the playground serves, keyed as Nitro keys it. */
const EXPECTED_ROUTE_KEYS = [
  "'/api/boom': {",
  "'/api/rogue-status': {",
  "'/api/specifier-probe': {",
  "'/api/users/:id': {",
]

/** The tags of the three variants `/api/users/:id` declares (SPEC.md §1). */
const DECLARED_TAGS = ['user-not-found', 'user-suspended', 'forbidden']

/**
 * Where the compile-time probe is written.
 *
 * `.nuxt/` is a dot-directory, which TypeScript's wildcard expansion skips — so
 * the probe is invisible to `vue-tsc`, to eslint and to knip, and reaches the
 * program only as the harness's explicit root file. Everything it imports
 * arrives through the generated tsconfig's `paths`.
 */
const PROBE_PATH = join('.nuxt', 'handler-errors-probe.ts')

const WORKSPACE = mkdtempSync(join(tmpdir(), 'nuxt-handler-errors-app-'))

afterAll(() => {
  rmSync(WORKSPACE, { recursive: true, force: true })
})

function probeSource(): string {
  const vocabulary = join(PACKAGE_ROOT, 'test/types/vocabulary')

  return [
    `import type { MatchedRoutes } from 'nitropack/types'`,
    `import type { TypedApiErrors } from '${TYPES_SPECIFIER}'`,
    `import type { Expect, IsNever } from '${vocabulary}'`,
    ``,
    `declare module '${TYPES_SPECIFIER}' {`,
    `  interface TypedApiErrors {`,
    // SPEC.md §4.5's transient state, declared rather than raced for: this map
    // lands ~26 ms *ahead* of Nitro's, so for that window it holds a key
    // `InternalApi` does not.
    `    '/api/ghost': { get: { tag: 'ghost', status: 404 } }`,
    `  }`,
    `}`,
    ``,
    `export type Declared = TypedApiErrors['/api/users/:id']['get']`,
    ``,
    // Resolved against the app's *real* generated `InternalApi`.
    `export type Ghost = MatchedRoutes<'/api/ghost'>`,
    `type _ghostIsUnreachable = Expect<IsNever<Ghost>>`,
    ``,
  ].join('\n')
}

/**
 * Re-point the playground's one reach into the suite at an absolute path.
 *
 * `playground/server/api/users/[id].get.ts` imports the assertion vocabulary as
 * `'../../../../test/types/vocabulary'`, which is four levels up — and out of a
 * copy in the system temp directory that lands nowhere. Left alone it is the
 * one `TS2307` standing between this file and SPEC.md §9.5 rule 3, which is
 * worth more than the edit costs: without a clean-program assertion a fixture
 * that stopped compiling for an unrelated reason would pass while proving
 * nothing.
 */
function reanchorSuiteImport(root: string): void {
  const path = join(root, 'server/api/users/[id].get.ts')
  const source = readFileSync(path, 'utf8')
  const reanchored = source.replace(
    `'../../../../test/types/vocabulary'`,
    `'${join(PACKAGE_ROOT, 'test/types/vocabulary')}'`
  )

  if (reanchored === source) {
    throw new Error(
      `Expected ${path} to import the suite vocabulary by relative path.`
    )
  }

  writeFileSync(path, reanchored)
}

/**
 * An emitted map with its route blocks removed — the banner, the two imports,
 * the `declare module` wrapper and the closing `export {}`.
 *
 * Route blocks are the only lines the emitter indents four spaces, which is why
 * that is the filter.
 */
function fileShell(source: string): string {
  return source
    .split('\n')
    .filter((line) => !line.startsWith('    '))
    .join('\n')
}

/** One built app: where it is, what the module wrote, and its probe compiled. */
interface BuiltApp {
  readonly root: string
  /** The emitted map's text, so path-referentiality can be a byte comparison. */
  readonly map: string
  readonly compilation: Compilation
}

/**
 * Copy the playground, optionally edit it, run `nuxt prepare`, read back what
 * the module wrote and compile the probe against it.
 *
 * `nuxt prepare` rather than a full build: `types:extend` fires inside Nitro's
 * `writeTypes`, which is exactly what `prepare` runs, and it costs ~2.5s.
 */
function buildApp(name: string, edit?: (root: string) => void): BuiltApp {
  const root = join(WORKSPACE, name)

  cpSync(PLAYGROUND, root, {
    recursive: true,
    filter: (source) => !NOT_COPIED.test(source),
  })
  symlinkSync(join(PLAYGROUND, 'node_modules'), join(root, 'node_modules'))
  reanchorSuiteImport(root)
  edit?.(root)

  execFileSync(
    join(PACKAGE_ROOT, 'node_modules/.bin/nuxt'),
    ['prepare', root],
    {
      cwd: PACKAGE_ROOT,
      stdio: 'pipe',
    }
  )

  const mapPath = join(root, MAP_PATH)
  if (!existsSync(mapPath)) {
    throw new Error(
      [
        `\`nuxt prepare\` produced no map at ${MAP_PATH}.`,
        'Either the type template was never registered, or it was emitted',
        "somewhere other than Nitro's types directory — where every specifier",
        'in it would resolve to nothing, silently.',
      ].join('\n')
    )
  }

  writeFileSync(join(root, PROBE_PATH), probeSource())

  const harness = createTypeHarness({
    ts,
    rootDir: root,
    tsconfigPath: join(root, '.nuxt/tsconfig.json'),
  })

  return {
    root,
    map: readFileSync(mapPath, 'utf8'),
    compilation: harness.compileAlone(join(root, PROBE_PATH)),
  }
}

let app: BuiltApp

beforeAll(() => {
  app = buildApp('base')
}, 180_000)

describe('the generated map, in a real Nuxt app', () => {
  it('compiles the whole app clean, with the map in the program', () => {
    // SPEC.md §9.5 rule 3, and the reason every claim below can be believed:
    // without it a probe that stopped compiling for an unrelated reason would
    // take the rendering assertions down with it silently. Nothing is filtered
    // by file — a positive fixture whose *app* stopped compiling is not a
    // passing fixture.
    assertNoDiagnostics(app.compilation)
  })

  it('lands in Nitro’s own types directory, under the build directory', () => {
    // `buildApp` throws if it is not there, so this records what the file is.
    // The directory is not a preference (SPEC.md §4.2): every specifier in the
    // file is relative to it, and moving the file one level up leaves the whole
    // map resolving to nothing with no diagnostic anywhere.
    expect(app.map).toContain('Generated by @dphonys/nuxt-handler-errors')
  })

  it('seeds a cold start with the same file shell it later replaces', () => {
    // SPEC.md §4.2's third reason for a type template: `nuxi dev` races
    // `writeTypes` against `buildNuxt`, so the template can be asked for its
    // contents before `nitro:init` has fired, and a `/// <reference>` to a file
    // that is not a module is a dangling one.
    //
    // **This currently holds by construction** — `EMPTY_MAP` is the emitter's
    // own `renderFile` applied to no routes — and saying so is the point. The
    // regression it guards against is the seed being spelled a second time,
    // which is where it was written first and what would let a banner, a
    // specifier or the closing `export {}` drift with nothing to notice. The
    // cold-start render itself is not observable from here: by the time
    // `prepare` returns, the populated one has already replaced it. `pnpm
    // dev-race` is where a genuinely cold start happens.
    expect(fileShell(EMPTY_MAP)).toBe(fileShell(app.map))
  })

  it('keys every route the app serves, and keys them as Nitro does', () => {
    for (const key of EXPECTED_ROUTE_KEYS) expect(app.map).toContain(key)

    // Nitro's own `[id]` → `:id` rewrite and its own extension stripping,
    // arrived at by re-running Nitro's loop rather than reimplementing it.
    expect(app.map).toContain(
      `typeof import('../../server/api/users/[id].get').default`
    )
  })

  it('augments the module’s own specifier, and closes as a module', () => {
    // Never Nitro's namespace (SPEC.md §4.2): a future Nitro release owning
    // this name would break consumers silently, and `TypedApiErrors` appears in
    // every wrapper signature, so declaring it there would hand this module's
    // public surface a second owner.
    expect(app.map).toContain(`declare module '${TYPES_SPECIFIER}' {`)
    expect(app.map).not.toContain(`declare module 'nitropack/types'`)
    expect(app.map.trimEnd().endsWith('export {}')).toBe(true)
  })

  it('is hoisted onto every generated tsconfig', () => {
    // SPEC.md §4.2's second load-bearing string, asserted through its effect.
    // Removing `typescript.hoist.push(…)` empties all three of these.
    for (const config of GENERATED_TSCONFIGS) {
      expect(readFileSync(join(app.root, '.nuxt', config), 'utf8')).toContain(
        `"${TYPES_SPECIFIER}"`
      )
    }
  })

  it('is referenced from the app, shared and server programs', () => {
    for (const { flag, file } of CONTEXT_REFERENCES) {
      expect(
        readFileSync(join(app.root, file), 'utf8'),
        `addTypeTemplate({ …, ${flag}: true }) should have written ${file}`
      ).toContain('nuxt-handler-errors.d.ts')
    }
  })

  it('resolves: the declared union carries this route’s real tags', () => {
    // The assertion this whole file exists for. Tags render **double**-quoted:
    // they are synthesised by the checker out of an object literal's inferred
    // type rather than written in an annotation (SPEC-AMENDMENTS item 7).
    const rendered = app.compilation.renderHover('Declared')

    for (const tag of DECLARED_TAGS) expect(rendered).toContain(`"${tag}"`)
    expect(rendered).toContain('requiredRole')
  })

  it('holds a key Nitro’s interface does not, unreachably (SPEC.md §9.6)', () => {
    // The dev-server race, asserted structurally rather than statistically. The
    // probe declares `/api/ghost` on the map and nothing declares it on
    // `InternalApi` — the shape the convergence window produces — and
    // `MatchedRoutes` derives its key universe from `keyof InternalApi`, so the
    // key is unreachable by construction. That is why SPEC.md §4.5 measured
    // `misattributed: 0` rather than merely "few", and why no guard machinery
    // ships. `pnpm dev-race` is where the clock gets watched (SPEC.md §9.6).
    //
    // §9.6 asks for this hermetically, and it *is* hermetic — in
    // `test/types/unreachable-map-key.test.ts`. Re-taken here because this
    // program resolves it against the app's **real generated `InternalApi`**
    // rather than a hand-written stand-in, and the program was already built.
    expect(app.compilation.renderHover('Ghost')).toBe('never')
  })
})

describe('path-referentiality, in a real Nuxt app (SPEC.md §4.4)', () => {
  /** The same app with one variant added to a catalogue. No route changes. */
  let edited: BuiltApp

  beforeAll(() => {
    edited = buildApp('content-edit', (root) => {
      const path = join(root, 'shared/errors/user.ts')

      writeFileSync(
        path,
        readFileSync(path, 'utf8').replace(
          "  'user-suspended'",
          [
            `  'user-rate-limited': { status: 429, payload: payload<{ retryAfter: number }>() },`,
            `  'user-suspended'`,
          ].join('\n')
        )
      )
    })
  }, 180_000)

  it('leaves the emitted file byte-identical after a content-only edit', () => {
    // SPEC.md §4.4's mandate, in the real app rather than only in the pure
    // function. Nitro never re-runs `writeTypes` on a `change` event and gets
    // away with it only because its output is an import expression the compiler
    // re-resolves on every edit; anything that resolved *values* at emit time
    // would go stale here with no watcher that would ever fix it.
    expect(edited.map).toBe(app.map)
  })

  it('and the compiler sees the new variant anyway', () => {
    // The other half, and the half a byte comparison cannot make: identical
    // output would be worthless if the type were stale too.
    const rendered = edited.compilation.renderHover('Declared')

    expect(rendered).toContain('"user-rate-limited"')
    expect(rendered).toContain('retryAfter')
  })
})
