import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'

// The map, produced by a real Nuxt build. This is the only layer that catches
// the type-generation hook silently ceasing to fire. `nuxt prepare` rather
// than a full build: `types:extend` fires inside Nitro's `writeTypes`, which
// is exactly what `prepare` runs. The claims here are structural; that the
// emitted text *resolves* is `test/types/emitted-map.test.ts`'s job.

const PACKAGE_ROOT = fileURLToPath(new URL('../..', import.meta.url))
const FIXTURE = join(PACKAGE_ROOT, 'test/fixtures/basic')

// Where the map must land: Nitro's `typesDir`. Written out rather than
// imported from `src/module.ts` - a test that took the path from the code
// under test would follow the file wherever it moved and stay green.
const MAP_PATH = join('.nuxt', 'types', 'nuxt-typed-handler.d.ts')

/** The umbrella's own specifier: hoisted, and the request-inputs map's target. */
const OWN_SPECIFIER = '@dphonys/nuxt-typed-handler/types'

/** The errors parent's specifier, as its slot emits it: the errors map's target. */
const ERRORS_SPECIFIER = '@dphonys/nuxt-handler-errors/types'

/**
 * The generated tsconfigs the hoist entry has to reach: the root one and the
 * app program it references, plus Nitro's and the shared one. Not
 * `tsconfig.node.json` - the map is not registered for the node program,
 * which has no call sites.
 */
const HOISTED_TSCONFIGS = [
  'tsconfig.json',
  'tsconfig.app.json',
  'tsconfig.server.json',
  'tsconfig.shared.json',
]

// The `/// <reference>` each context reaches the map through, and the
// `addTypeTemplate` flag that puts it there - the obvious `{ nitro: true }`
// buys only the third row.
const CONTEXT_REFERENCES = [
  { flag: 'nuxt', file: join('.nuxt', 'nuxt.d.ts') },
  { flag: 'shared', file: join('.nuxt', 'nuxt.shared.d.ts') },
  { flag: 'nitro', file: join('.nuxt', 'types', 'nitro-nuxt.d.ts') },
]

/** A route added after the first `prepare`, to see the map refreshed. */
const ADDED_ROUTE = join(FIXTURE, 'server/api/added.get.ts')

function prepare(): string {
  execFileSync(
    join(PACKAGE_ROOT, 'node_modules/.bin/nuxt'),
    ['prepare', FIXTURE],
    { cwd: PACKAGE_ROOT, stdio: 'pipe', timeout: 240_000 }
  )

  const mapPath = join(FIXTURE, MAP_PATH)
  if (!existsSync(mapPath)) {
    throw new Error(
      [
        `\`nuxt prepare\` produced no map at ${MAP_PATH}.`,
        'Either the type template was never registered, or it was emitted',
        "somewhere other than Nitro's types directory - where every specifier",
        'in it would resolve to nothing, silently.',
      ].join('\n')
    )
  }

  return readFileSync(mapPath, 'utf8')
}

/** The `declare module` blocks of a map, by the specifier each augments. */
function blocksOf(source: string): Record<string, string> {
  const blocks: Record<string, string> = {}
  const pattern = /^declare module '([^']+)' \{\n([\s\S]*?)^\}$/gm

  for (const match of source.matchAll(pattern)) {
    const [, specifier, body] = match
    if (specifier !== undefined && body !== undefined) blocks[specifier] = body
  }

  return blocks
}

let map: string

beforeAll(() => {
  rmSync(ADDED_ROUTE, { force: true })
  map = prepare()
}, 300_000)

afterAll(() => {
  rmSync(ADDED_ROUTE, { force: true })
})

describe('the generated map, in a real Nuxt app', () => {
  it('lands in Nitro’s own types directory, generated by this module', () => {
    // Every specifier in the file is relative to that directory; moving the
    // file one level up leaves the whole map resolving to nothing.
    expect(map).toContain('// Generated by nuxt-typed-handler - do not edit')
  })

  it('carries both maps, each augmenting its own specifier, and closes as a module', () => {
    const blocks = blocksOf(map)

    expect(Object.keys(blocks)).toEqual([ERRORS_SPECIFIER, OWN_SPECIFIER])
    expect(blocks[ERRORS_SPECIFIER]).toContain('  interface KnownApiErrors {')
    expect(blocks[OWN_SPECIFIER]).toContain(
      '  interface KnownApiRequestInputs {'
    )

    // Never Nitro's namespace: a future Nitro release owning this name would
    // break consumers silently.
    expect(map).not.toContain(`declare module 'nitropack/types'`)
    expect(map.trimEnd().endsWith('export {}')).toBe(true)
  })

  it('keys every route the app serves in both maps, as Nitro keys them', () => {
    const blocks = blocksOf(map)

    for (const block of Object.values(blocks)) {
      expect(block).toContain(`    '/api/users/:id': {`)
      expect(block).toContain(`    '/api/users': {`)
      expect(block).toContain(`    '/api/legacy': {`)
    }

    // Nitro's own `[id]` → `:id` rewrite and extension stripping.
    expect(map).toContain(
      `typeof import('../../server/api/users/[id].get').default`
    )
  })

  it('reads the errors slot through the parent’s extractor, serialised', () => {
    expect(blocksOf(map)[ERRORS_SPECIFIER]).toContain(
      `'get': Simplify<Serialize<KnownErrorsOfHandler<typeof import('../../server/api/users/[id].get').default>>>`
    )
  })

  it('reads the request-inputs slot with Simplify alone - the input is the wire shape', () => {
    const block = blocksOf(map)[OWN_SPECIFIER] ?? ''

    expect(block).toContain(
      `'post': Simplify<RequestInputOfHandler<typeof import('../../server/api/users.post').default>>`
    )
    expect(block).not.toContain('Serialize')
  })

  it('imports each extractor from the specifier that owns it, once', () => {
    expect(
      map.split('\n').filter((line) => line.startsWith('import type'))
    ).toEqual([
      `import type { Serialize, Simplify } from 'nitropack/types'`,
      `import type { KnownErrorsOfHandler } from '${ERRORS_SPECIFIER}'`,
      `import type { RequestInputOfHandler } from '@dphonys/nuxt-handler-validation/types'`,
    ])
  })

  it('is hoisted onto every generated tsconfig', () => {
    // Removing `typescript.hoist.push(…)` empties all three of these.
    for (const config of HOISTED_TSCONFIGS) {
      expect(readFileSync(join(FIXTURE, '.nuxt', config), 'utf8')).toContain(
        `"${OWN_SPECIFIER}"`
      )
    }
  })

  it('is referenced from the app, shared and server programs', () => {
    for (const { flag, file } of CONTEXT_REFERENCES) {
      expect(
        readFileSync(join(FIXTURE, file), 'utf8'),
        `addTypeTemplate({ …, ${flag}: true }) should have written ${file}`
      ).toContain('nuxt-typed-handler.d.ts')
    }
  })

  it('keys a handler added after the first prepare, in both maps', () => {
    // The refresh, observed as far as a fresh process can see it: a route
    // that did not exist at the first `prepare` is keyed in both maps after
    // the next. That the `types:extend` hook is what re-renders the template
    // *within* a build is `test/unit/module-setup.test.ts`'s claim.
    expect(map).not.toContain(`'/api/added'`)

    writeFileSync(
      ADDED_ROUTE,
      [
        `import { defineEventHandler } from 'h3'`,
        ``,
        `export default defineEventHandler(() => ({ added: true }))`,
        ``,
      ].join('\n')
    )

    const refreshed = prepare()

    for (const block of Object.values(blocksOf(refreshed))) {
      expect(block).toContain(`    '/api/added': {`)
    }
  }, 300_000)
})
